### ISSUE TITLE
Revisión final de fichas #IAI

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#112]
Creo un nuevo issue para la revisión general de todas las fichas (está resultando un poco complicado ver de una por una). 

Ya están revisados y actualizados los archivos de formación y los PDF en la carpeta _Fichas formadas IAI (PDF + ID)_. Diana revisó y uniformó la bibliografía en todas, y yo revisé los últimos detalles de formación y generé los últimos PDF.

Queda pendiente:

- **Ficha de participantes:** Hay logos pendientes y detalles de formación (no sé si debemos escribir el nombre completo de cada institución debajo de cada logo o sólo las siglas). Mandé la versión actual A Bertha para que nos sugiera algo respecto a los logos.

Si hay algo más que revisar o comentar sobre las fichas, lo pueden hacer por acá. De todos modos mañana iré a LANCIS para lo que falte.

Gracias

**Comment by Didigar** [comment]
Hola @ovisnigra 
pues ayer le comente a @PaolaGomezPriego y dijo que si pusieramos los nombres de bajo de cada logo porque efectivamente no todos dicen lo que son o tienen iniciales, por cuestiones de espacio podemos reducirlos para que queden mejor (se lo sugeri a Pao y dijo que si, no se si estes de acuerdo).
Cuando vea a Bertha le pregunto si lo checo....
Estoy al pendiente. saludos

**Comment by Nayita** [comment]
Sergio:

Ya están los textos de las fichas de objeto frontera y síntesis MEGADAPT para que los puedas sustituir en los insumos de las carpetas correspondientes. En el caso de la ficha de objetos de frontera, Luis le ha pedido a Fidel que genere 2 nuevas imágenes. Así que esas imágenes faltan.

Saludos

**Comment by Nayita** [comment]
Sergio, hicimos una pequeña corrección a la ficha de modelación multicriterio en el archivo id. Me comenta Diana que tu haces el PDF para que lo hagas nuevamente, por favor. Gracias.

**Comment by ovisnigra** [comment]
Anotado. Entonces:

1) Uniformar lo de los nombres debajo de los logos en la ficha de participantes.
1a) A Bertha ya le escribí, creo que no ha tenido tiempo de verlo. Lo importante (creo) es ver si conseguimos los logotipos que nos faltan.
2) Volver a formar el texto de las fichas de Objetos de Frontera y de Síntesis con el nuevo archivo. Pregunta: ¿ya revisaron la bibliografía de estas también?
3) Queda pendiente recibir 2 nuevas figuras para la ficha de Objetos de Frontera.
4) Revisar la ficha de Modelación multucriterio y generar el PDF de nuevo.

PD: Llego al Labo como a las 11. Nos vemos al rato.

**Comment by Nayita** [comment]
Con respecto a la bibliografía de ambas fichas, es posible que solo sustituyas el texto?
La bibliografía en tus archivos de id están bien y es la misma no se agregó ni se quitó nada.

Todo lo demás OK.

**Comment by ovisnigra** [comment]
ok. Enterado de lo de las bibliografías.

**Comment by PaolaGomezPriego** [comment]
Me avisan cuando estén todas?

**Comment by edithvilla** [comment]
la imagen del mapa de Promedio de eventos de inundación del PNAS está en:

Q:\Procesamiento\Mapas\AguaSuperficial

también la mandé por correo a Nadia

**Comment by ovisnigra** [comment]
recibida

**Comment by Nayita** [comment]
Se han hecho correcciones a la ficha de Modelos mentales y de Sistemas socio-ecológicos en los archivos de id, para que las cheques y generes los PDF, por favor.

La figura 1 de la ficha de objetos de frontera ya está en insumos. Se llama PromedioEncharcamiento_PNAS. El pie de figura es el siguiente Fig. 1. Eventos de inundación en colonias de la Ciudad de México. Aumentar la resiliencia urbana puede ayudar a las ciudades a superar mejor este tipo de desastres naturales. Fuente de datos: Unidad Tormenta, Sistema de Aguas de la Ciudad de México.

La ficha de vulnerabilidad va a cambiar en texto nuevamente. Te envío la nueva versión cuando esté. 
Gracias

**Comment by ovisnigra** [comment]
Ya revisadas y actualizados los PDF de: 

- Síntesis
- Modelos mentales
- y Sist. Socio-ecológicos. 

- Trabajando en Objetos de Frontera (sigue pendiente pie de figura de la Fig. 2).

- Esperando nuevo texto de Vulnerabilidad.

**Comment by PaolaGomezPriego** [comment]
Ya está el texto nuevo de vulnerabilidad. Ojo lleva una figura nueva (repetida de la ficha de objetos de frontera).

**Comment by PaolaGomezPriego** [comment]
Me etiquetan cuando pueda revisar el resto terminado.

**Comment by Nayita** [comment]
El texto de vulnerabilidad nuevo tiene las siglas de Paola y está en la carpeta de insumos.

**Comment by ovisnigra** [comment]
Terminada ficha Objetos de frontera (con figuras nuevas). Ya actualizado el PDF (Ojo: Sigue Pendiente pie de figura de la Fig. 2)

Sigo con la de Vulnerabilidad.

**Comment by Nayita** [comment]
El pie de figura es Fig. 2. Ejemplo de objeto de frontera en MEGADAPT. Este pie de figura aplica para la ficha de objeto de frontera y la de vulnerabilidad.

Si, toma texto solamente. Gracias

**Comment by ovisnigra** [comment]
got it

**Comment by ovisnigra** [comment]
Listo. Ya están listas
- Objetos de frontera (con el pie que faltaba y la figura nueva)
- Vulnerabilidad (con el nuevo texto y la nueva figura con su pie. OJO: La figura tuvo que entrar ligeramente reducida porque si no no cabía).

- ahora sólo queda pendiente la Ficha de participantes (estoy viendo cómo acomodar todos los nombres y aún faltan logos)

**Comment by Nayita** [comment]
ok, las dos, saludos

**Comment by Nayita** [comment]
Paola dice que la ficha de participantes ya quede como está para esta entrega. Bertha está muy ocupada y no va a poder ayudarnos por ahora. Gracias

**Comment by ovisnigra** [comment]
OK. Sólo díganme qué hago con las instituciones de las que no encontré logo ¿las quito?

**Comment by Nayita** [comment]
Déjalas con el asterisco

**Comment by ovisnigra** [comment]
okas. les aviso al rato cuando esté lista

**Comment by PaolaGomezPriego** [comment]
Avísale a Diana porque dependemos de esta ficha para cerrar el PDF final de entrega.

**Comment by PaolaGomezPriego** [comment]
Y por cierto, no funciona esto de generar un issue como este cuando todavía los de las fichas independientes están abiertos. Es confuso hacer la revisión.

**Comment by ovisnigra** [comment]
Ya está la de ficha de participantes.

**Comment by ovisnigra** [comment]
A mi me funcionó así porque me costaba rastrear las pequeñas correcciones que salían en cada issue de las fichas (no sé si funcionó para Nadia y Diana). No cerré las anteriores esperando la revisión final.

**Comment by Nayita** [comment]
oki doki

**Comment by ovisnigra** [comment]
Bertha ya mandó sus correcciones, están en este PDF como comentarios:

https://www.dropbox.com/s/o1i2ktxfx9utykg/Ficha%20Participantes%20IAI_BHA.pdf?dl=0

Transcribo el correo que me mandó Bertha: 

> Lo acabo de revisar, pero me comentan que lo van a dejar lo más general posible por los tiempos. Por favor, los de Secretaría de Salud son super importantes así como CENTLI, lo demás son detalles. Puse varios comentarios en el .pdf.

**Comment by Nayita** [comment]
Revisadas.

**Comment by Didigar** [comment]
listo me quitooo

**Comment by ovisnigra** [comment]
cierro issuie porque daremos seguimiento en otro lugar
