### ISSUE TITLE
Investigar y crear estilos de celda Excel #LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#122]
Paola pidió investigar como hacer el equivalente a una plantilla de estilos en Excel

**Comment by ovisnigra** [comment]
En este link a una matriz de conflictos que realicé para Pacífico Norte ya hay varios estilos de celda creados.
¿a quieren revisar? ¿es esto lo que necesitaban?

https://www.dropbox.com/s/v0napbtobd95pl1/Matriz%20de%20conflictos%20a%20distancia_FINAL.xls?dl=0

**Comment by PaolaGomezPriego** [comment]
Si Justo. necesitamos ahora que sea consistente con la plantilla de documentos de Lancis.

**Comment by ovisnigra** [comment]
enterado

**Comment by ovisnigra** [comment]
Listo. Se crearon estilos de celda en el documento muestra:

`Dropbox (LNCS)/Material grafico-editorial LANCIS/Plantillas informes\Estilos_celdas.xlsx`

**Comment by PaolaGomezPriego** [comment]
Ya lo revisé. Se pueden generar algunos criterios generales Ya vi que tu mismo ya rompiste algunas reglas básicas, como número de decimales, alineado y líneas intermedias. Porque no incluyes un par de tablas mas complejas para que se vean como pueden quedar.

**Comment by ovisnigra** [comment]
OK, haré lo de incluir algunos casos más complejos como muestra.
También haré una versión comentada e incluiré los criterios a aplicar para que sea más claro el uso de los estilos de celda, que por cierto tienen sus limitantes y diferencias respecto al uso que le damos en word.

Por lo pronto comento sobre lo que comentas:

- Las reglas básicas serán las mismas de la plantilla de documentos. 
- La cantidad de decimales no se especifica en el estilo de celda porque es variable (a veces no hay decimales y a veces hay más de dos)
- Las alineaciones también son variables, pues en elcaso de los números dependerán de la extensión de las cifras.

**Comment by ovisnigra** [comment]
Actualizado el Excel, con comentarios, correcciones y añadidos.

**Comment by PaolaGomezPriego** [comment]
listo para cerrarse
