### ISSUE TITLE
Poner MRD de las gráficas en una carpeta en Dropbox #General

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#124]

**Comment by edithvilla** [comment]
Coloqué las los archivos correspondiente a las gráficas que se encuentran en el informe de IAI
en las carpetas Grafica_BarrasApiladas y Grafica_pie en
Dropbox (LNCS)\Repositorio_R\Graficas

**Comment by Nayita** [comment]
Los markdown están en la carpeta Gráficas Markdown dentro de la carpeta Repositorio R. Falta clasificarlas.
Corresponden a los MRD hechos para Cananea; de IAI, para Sergio Flores, Presentación UNIVERSUM y MEGADAPT están solamente las que he hecho. Faltan las de Diana

**Comment by Nayita** [comment]
IAI también ya están todos en la carpeta. Diana no revises esa carpeta

**Comment by Didigar** [comment]
Listo
