### ISSUE TITLE
Realizar plantilla en QGIS #Planeación Colaborativa

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#134]
Paola me proporcionará mapas para que yo pueda replicarlos en QGIS

**Comment by PaolaGomezPriego** [comment]
Compartí una carpeta en el dropbox del labo llamado "PlantillaQuantum"  con varios modelos.

**Comment by edithvilla** [comment]
http://www.qgis.org/es/site/about/screenshots.html

https://www.flickr.com/groups/qgis/pool/

http://www.qgistutorials.com/es/docs/making_a_map.html

https://mappinggis.com/2015/06/como-crear-una-composicion-de-mapa-con-qgis/

**Comment by edithvilla** [comment]
Lista plantilla de 
Crecimiento urbano
