### ISSUE TITLE
Presentación #Universum - Revisión general y arreglar figuras

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#136]
Revisión general y hacer las figuras más grandes (o al menos la tipografía para que no se pierda).

Cualquier otra instrucción o algo en particular que quieran que revise, pueden usar este _issue_

**Comment by ovisnigra** [comment]
Lista la nueva versión:

https://www.dropbox.com/s/hwsl87dv5hvzcl2/Presentaci%C3%B3n_UNIVERSUM_SBC_FEB2017.pptx?dl=0

**Comment by PaolaGomezPriego** [comment]
Listo..

**Comment by PaolaGomezPriego** [comment]
Ya se hizo la primer parte de observaciones..
