### ISSUE TITLE
Estudiar Markdown para iniciar curso a finales de abril

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#138]
Me reuniré con ex-socio estratégico José Luis Acosta para ver posibilidad de curso o asesoría.

**Comment by ovisnigra** [comment]
Creo que esto nos interesa. si tienes chance de verlo, habrá que platicarlo.

Te mando el link del demo: [Reveal.js, HTML presentation framework](http://lab.hakim.se/reveal-js/#/)

**Comment by PaolaGomezPriego** [comment]
si.. eso ya lo había visto.. ta buenísimo!!  ya puedes hacerlo?

**Comment by ovisnigra** [comment]
Sí, ya estoy haciendo pruebas. también estoy empezando a pasar algunas fichas de IAI a Markdown.

**Comment by ovisnigra** [comment]
cierro este issue, pues es una labor continuada y ligada a lo que estpy haciendo con la página web.
