### ISSUE TITLE
Correcciones ficha participantes #MEGADAPT

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#142]
Académicos agregar:
-IMTA
Gobierno CDMX:
-Agregar Secretaria de salur de CDMX www.salud.cdmx..gob.mx
-Agregar jurisdicción sanitaria de Iztapalapa, xochimilco y Magdalena contreras 
Gobierno Federal:
-Secretaria de salud www.gob.mx/salud
-Registro Agrari Nacional (RAN)
Asociaciones civiles:
-Dejar sólo El Molino y quitar todo lo demás que diga Molino
Gobierno local:
-Corregir de director a dirección de protección civil
No gubernamental:
-COMDA aqui esta el logo y este es el nombre Coalición de Organizaciones Mexicanas por el Derecho al Agua (COMDA)
https://www.google.com.mx/search?q=www.comda.org.mx&rlz=1C1WPZB_enMX681MX687&espv=2&biw=1745&bih=885&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwjL_ej0pqfSAhVL_4MKHcOeBIYQ_AUICCgD&dpr=1.1#imgrc=diJKI549bD3PAM:
-Podemos quitar a CORENA ya que es parte de SEDEMA

**Comment by ovisnigra** [comment]
Recibido Diana. Se te olvidó asignarme el issue, se me estaba perdiendo.

**Comment by Didigar** [comment]
la etiqueta ahi ta dices que falto esto @ovisnigra ???

**Comment by ovisnigra** [comment]
Dudas: 

¿Deberían ir en Gobierno local (sin logo)?

1. Delegación Tlalpan
2. jurisdicción sanitaria de Iztapalapa, xochimilco y Magdalena contreras

Además:

3. En Gobierno local tenemos Dirección de Protección civil y en gobierno CDMX tenemos la Secretaría de Protección Civil ¿está bien así son la misma?
4. También en Gobierno local dice: "Secretario de Patrimonio de la Delegación Xochimilco" ¿debería ser "Secretaría".

Gracias quedo al pendiente. Todas las demás correcciones ya se integraron al ID.

**Comment by ovisnigra** [comment]
?

**Comment by Didigar** [comment]
jajaja ashhhhhh me equivoque este no era perdón me retirare lenta y silenciosamente  ...........

**Comment by Didigar** [comment]
Pero estoy en esto @ovisnigra

**Comment by ovisnigra** [comment]
jojojo. ok

**Comment by Didigar** [comment]
Ya hable con Bertha y estas son las correcciones...
-Quitar a la delegación Tlalpan (de todo)
-Jurisdicción sanitaria en lista de local  poner Jurisdicción sanitaria de xochimilco, iztapalapa y Magdalena 
-

**Comment by ovisnigra** [comment]
ok. las voy aplicando

**Comment by ovisnigra** [comment]
Listo. Ya aplicadas las últimas correcciones

**Comment by Didigar** [comment]
listo

**Comment by Didigar** [comment]
@ovisnigra recuerda mandarme el word del ID para poner correcciones sobre ese

**Comment by ovisnigra** [comment]
ya está en la carpeta de insumos de la ficha se llama **Participantes - Captura en Word.docx**

**Comment by Didigar** [comment]
@ovisnigra Ya quedo editado, volamos muchas asi que quedara mas corta. Edite el wod con revisión, cualquier cosa estoy al pendiente, aqui puse en word 
https://www.dropbox.com/work/IAI/procesamiento/fichas%20megadapt%20iai/fichas%20formadas%20iai%20(pdf%20%2B%20id)/Participantes%20Ficha/Insumos%20y%20auxiliares?preview=Participantes+-+Captura+en+Word(editado).docx

**Comment by ovisnigra** [comment]
ok. lo reviso. salu2

**Comment by ovisnigra** [comment]
ya está para que la revises (en el mismo lugar de antes)

**Comment by Didigar** [comment]
Ok, ya se lo envié a Bertha para que lo cheque, si me da su Vo. Bo. cierro el achu

**Comment by ovisnigra** [comment]
puedes quitar tu etiqueta
;-)

**Comment by Didigar** [comment]
@ovisnigra Ya tengo las nueva correcciones:
1- Eliminar a los académicos
2-En OCAVM agregar del en... Organismo de Cuenca Aguas del Valle de México
3- Eliminar a No gubernamental 
4- En Asociaciones civiles poner ATLITIC en minúsculas  (Atlitic)
5- Eliminar a CENTLI 
6- Nuevo cuadro que lleve el título (sugerido)....
# Residentes particulares de las colonias:
La Concepción
El Rosal
El Ocotal
Tierra Colorada
Santa Teresa
El Molino
Lomas de la Estancia
Miguel de la Madrid
Ex-Lienzo Charro
Desarrollo Urbano Quetzalcoatl
Tlaxopan I y II
Xicalhuacan
Tliziclipa 
Barrio de Tlacoapa
 
Y ya quedaría listo¡

**Comment by ovisnigra** [comment]
Lixto. Te lo dejo a que lo cierres tu si ya queda.

**Comment by Didigar** [comment]
@ovisnigra Sólo hay un detalle y así queda para mandársela a Hallie ...
En gobierno local: Xochimilco  dice ...
Dirección de protección Civil
y debe ser 
Dirección de Protección Civil (la p debe ser mayúscula; Protección)
Es todo, cambio y fuera, conejo pachón sigue trabajando y al pendiente ...

**Comment by ovisnigra** [comment]
Enterado conejo pachón. Cambio realizado y archivos listos y actualizados.

Out.

(PD: ahi lo cierras plis)

**Comment by Didigar** [comment]
@ovisnigra ya la envié, cerraré esto por el momento...si me la regresan con correcciones o algo abro el achu de nuez

**Comment by Didigar** [comment]
@ovisnigra Ya recibí respuesta de Hallie y me comenta que hay que quitar a NSF de instituciones ya que es un financiador no un participante ... no se si lo deberiamos poner en otra categoría lo consultare con Paola y te aviso vale, por mientras hay que quitarlo ...
Seguimos al pendiente ciaooooooo

**Comment by ovisnigra** [comment]
chiro

**Comment by ovisnigra** [comment]
enterado. lo quito y espero instrucciones.

**Comment by Didigar** [comment]
@ovisnigra Quedará asi...
ponemos una primera categoría que se va a llamar ## Financiamiento y ahi van a ir:
-NSF 
-IAI
Vale, cambio y jjuerassss

**Comment by Didigar** [comment]
@ovisnigra creo que no lo has visto....

**Comment by ovisnigra** [comment]
no la había visto. mañana lo aplico

**Comment by ovisnigra** [comment]
listo. ya aplicada la última corrección de "Financiamiento"

**Comment by Didigar** [comment]
listoooooo¡¡¡
