### ISSUE TITLE
Limpiar la imagen del artículo de subsidencia #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#148]
se lo mandé por correo el artículo

Hernandez_Espriu_etal_2014_DRASTICSg_Mexico.pdf

página 9, figuras a y c

**Comment by edithvilla** [comment]
Sergio, ya encontramos otras imágenes que están mejor. 

Tenemos imágenes en pdf por delegación te las mando por correo

**Comment by ovisnigra** [comment]
Listo. Ya están en la carpeta de trabajao de Sergio del servidor de Megadapt

**Comment by ovisnigra** [comment]
sí funcionaron @edithvilla ?

**Comment by edithvilla** [comment]
Hola!
Sii funcionaron gracias!!!

ya deberías cerrar este issue

**Comment by ovisnigra** [comment]
ok. también lo puedes cerrar tu ;)
