### ISSUE TITLE
Logotipo + Revisión de interfaz del Sistema de soporte #SIGPLAN

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#149]
antes de hacer el logo ver si se me ocurre una propuesta de nombre.

Revisar con Marco la interfaz del Sistema de Soporte.

**Comment by ovisnigra** [comment]
quito las etiquetas por ahora. cuando haya comentarios que atender etiquetamos. 

trabajando en el logo ya.

**Comment by ovisnigra** [comment]
Propuestas para logotipo:

https://www.dropbox.com/s/pxmk5yhd918yhoo/Propuestas%20Logo%20SIGPLAN.png?dl=0

**Comment by ovisnigra** [comment]
No he reicibido retroalimentción de esto Paola

**Comment by PaolaGomezPriego** [comment]
el vínculo caducó :(

**Comment by ovisnigra** [comment]
Atualizado:

https://www.dropbox.com/s/35nc1cwcygfv4p0/Propuestas%20Logo%20SIGPLAN.png?dl=0

también lo había mandado por correo a Daniela y Luis

**Comment by PaolaGomezPriego** [comment]
Si. ya lo había visto.. ya había decidido.. nomás no me acordaba de cual era..  Como ni Daniela, ni Luis emitieron opinión, queda el 1. Ya puedes cerrar el issue.

**Comment by ovisnigra** [comment]
OK queda el logo. Falta la interfaz.

**Comment by ovisnigra** [comment]
Queda archivo aquí

`Dropbox (LNCS)\Diseño gráfico LANCIS (Respaldo Sergio)\_Sistema de Soporte SIGPLAN`
