### ISSUE TITLE
Realizar tabla para registro #OIPA

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#156]

**Comment by Didigar** [comment]
@Nayita hice una tabla en excel que me pidió Paola para tener control de los requerimientos que hagamos vía acceso a la información sobre las mias ... se encuentra en la carpeta de drop box

**Comment by Nayita** [comment]
OK, ahí ingresaré la petición que he hecho de la gaceta. Gracias
