### ISSUE TITLE
Hacer GIF de crecimiento urbano para los escenarios e00 y e01 #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#167]

**Comment by edithvilla** [comment]
en espera de que Sergio tenga la paleta de colores lista

**Comment by edithvilla** [comment]
se pone en pausa hasta tener las nuevas corridas

**Comment by edithvilla** [comment]
@ovisnigra 

Necesitamos hacer el gis para el escenario e03 con las gráficas

**Comment by ovisnigra** [comment]
Listo en carpeta de Procesamiento

**Q:\Procesamiento\GIF Mapa Crecimiento Urbano**

Falta decidir dónde ponerlo en la Plataforma.
