### ISSUE TITLE
Corrección de gráfica de presentación universum para nueva presentación 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#168]
@ovisnigra Hola te mando el link de la gráfica que por instrucciones de Paola corregí (sólo quedaron estados costeros y le agregue los porcentajes) trate de ponerle los nuevos colores pero no tengo los "codigos" rgb para el color azul y rojo exactos ...
Aquí está el pdf y la imagen 

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_Humedal_Vpor.pdf

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_Humedal_Vpor.png

**Comment by ovisnigra** [comment]
recibida. la voy revisando

**Comment by ovisnigra** [comment]
Ya quedó integrada a la nueva versión de la presentación (slide 18, **Presentación_UNIVERSUM_SBC_Marzo2017.pptx**), en la carpeta de Presentación Universum.
