### ISSUE TITLE
Pruebas en plantilla QGIS de estilos y paletas de colores #MEGADAPT #Presentación Congreso

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#176]
Por ahora, instalando QGIS

**Comment by ovisnigra** [comment]
@edithvilla me mandará unas capas de prueba para empezar

**Comment by edithvilla** [comment]
@ovisnigra las capas de inundaciones (inunsacmex.shp) y enfermedades gastrointestinales (enfgastroageb)
están en en dropbox:

MEGADAPT_Integracion\Plataforma\PresentacionCongreso\sig

**Comment by edithvilla** [comment]
@ovisnigra ya están los raster de crecimiento urbano, temporalidad 2012-2014 y están en 

Q:\Procesamiento\OutputModelos\CrecimientoUrbano\e00

**Comment by edithvilla** [comment]
@ovisnigra ya están las capas muestra para precipitación y escurrimiento en:

Q:\Plataforma\PresentacionCongreso\sig\

**Comment by ovisnigra** [comment]
Mandé paletas de colores a Fidel para ir haciendo pruebas. Aquí el archivo con las propuestas:

https://www.dropbox.com/s/yn7cy2pzfkjur8p/Colores_MEGADAPT.pdf?dl=0

**Comment by ovisnigra** [comment]
el archivo SLD con los colores para precipitación está aquí:
https://www.dropbox.com/s/a2jt8x083amw29a/Precipitacion.sld?dl=0

**Comment by PaolaGomezPriego** [comment]
Cambiar la plantilla de verdes

**Comment by ovisnigra** [comment]
Enterado

**Comment by ovisnigra** [comment]
Ya revisadas las nuevas paletas con Fidel y Paola en el Anfiteatro. El archivo con los colores finales está en:

Q:\CarpetasTrabajo\Sergio\Presentación Congreso marzo 2017\Insumos y Auxiliares

se llama *Colores_MEGADAPT_v2.pdf*
