### ISSUE TITLE
Formación Ficha Transdisciplina #IAI

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#18]
DIA - Estado actual: Correcciones. Ya corregí la figura (traducir al español), en proceso de ajuste de formación.

**Comment by ovisnigra** [comment]
Sale figura anterior. Recibida nueva figura con instrucciones de Paola.

**Comment by PaolaGomezPriego** [comment]
¿Cuál es la pregunta?

**Comment by ovisnigra** [comment]
Necesito el pie de figura de la nueva figura plis.

**Comment by Didigar** [comment]
@ovisnigra aqui va lo del pie de figura ... (sorry) el pie de figura aqui es  # "Transdisciplina en MEGADAPT"

**Comment by Didigar** [comment]
@ovisnigra En la ficha de transdisciplina me falta mandarte una bibligrafia que hay que agregar pero creo que se la puedo agregar yo, igual que la referencia donde se menciona la figura ... hago los cambios y los guardo.

**Comment by ovisnigra** [comment]
Mándamelo cuando lo tengas si quieres, prefiero hacerlo yo si se puede. Ya que esté lo cerramos.

**Comment by Didigar** [comment]
ok... la bibliografía se la tengo que pedir a Luis, hoy mismo lo hago y te mando la info ...

**Comment by ovisnigra** [comment]
Formando a partir del nuevo texto de Word.

Observaciones:
1. La bibliografía no estaba en la captura. Revisar que la que está en la formación sea la correcta.
2. Mismo problema con el formato de los años en la bibliografía (ver issue, modelación multicriterio).

**Comment by ovisnigra** [comment]
ya revisada bibliografía y formación. actualizados ID y PDF en **Fichas formadas IAI (PDF + ID)**

**Comment by Didigar** [comment]
Listo cierro este achuu
