### ISSUE TITLE
Corrección de fichas 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#186]
@ovisnigra 
@Nayita 
Hay algunas correcciones de dedos que hay que cambiar en las fichas...
-En la ficha de síntesis:
En la segunda hoja en la sexta línea ...
que se realizó #  **en** entre el 17 y 20 de octubre de 2016 en (hay que quitar el "en"
 -En la ficha de Objetos frontera:
Hay párrafo que se repite en la sexta línea de la segunda hoja ...
La complejidad de MEGADAPT obliga a la utilización
de objetos en la frontera de diversa índole. El denominador
común entre ellos es el propósito de hacer accesible
al mayor número de personas el conocimiento sobre
la vulnerabilidad a riesgos socio-hidrológicos en la Zona
La complejidad de MEGADAPT obliga a la utilización de
objetos de frontera de diversa índole y que se aplican
a lo largo del proyecto de manera iterativa, interactiva
y progresiva. El propósito de hacer accesible al mayor
número de personas el conocimiento sobre la vulnerabilidad
al riesgo a lo que se denominan riesgos sociohidrológicos
por inundaciones, escasez de agua y afectaciones
a la salud en la Zona Metropolitana de la Ciudad
de México.
-Modelación hidrológica:
EN el tercer parrafo d ela primera hoja...
La modelación hidrológica es una herramienta fundamental en la gestión
sostenible de cuencas tanto urbanas como rurales (una cuenca es un
territorio # **en** cuyas aguas afluyen todas a un mismo río, lago o mar). (Podemos quitar el en)
Propongo,puedo quitarlo yo del ID y generar un nuevo PDF Sergio si estas de acuerdo (pero creo que en la de Objetos de frontera si es mucho texto y tal vez se mueva algo) por el momento son los únicos cambios que hay.

**Comment by ovisnigra** [comment]
No te preocupes yo hago las correcciones que indicas.

**Comment by ovisnigra** [comment]
* __Ficha Síntesis:__ Ya ví que ya la corregiste. Ya generé de nuevo el PDF.

 * __Objetos de Frontera:__ ¿Cómo debe de quedar? ¿elimino la primera parte?

la que dice: 
> La complejidad de MEGADAPT obliga a la utilización de objetos en la frontera de diversa índole. El denominador común entre ellos es el propósito de hacer accesible al mayor número de personas el conocimiento sobre la vulnerabilidad a riesgos socio-hidrológicos en la Zona

 * __Modelación Hidrológica:__

**Comment by Nayita** [comment]
Si, elimina toda esa primera parte en la de Objetos de Frontera, por favor. Gracias

**Comment by Didigar** [comment]
@ovisnigra Sergio si tienes alguna duda aca ando pero puedes tomar como referencia (y eso olvide decírtelo ayer) están los textos en word que genere a partir del ID, ahí esta como debe quedar, creí que se entendería mejor si ponía los cambios puntuales en el achu, pero bueno puedes tomar esos word de referencia . Saluditos y buen puente.

**Comment by ovisnigra** [comment]
Correcto. ya quedó.

Saludos. buen fin

**Comment by Nayita** [comment]
ok, Hecho y revisado

**Comment by Didigar** [comment]
@ovisnigra hooola de nuez... pues me percaté de que síntesis MEGADAPT aun tiene guiones y deben ser paréntesis .... En esta parte :
Este esquema se enfoca a entender cómo la vulnerabilidad de la Zona Metropolitana de la Ciudad de México evoluciona ante los riesgos asociados a las inundaciones, a la escasez de agua y a la salud. Se parte de la premisa que la vulnerabilidad—o sea, la propensión de  un  sistema  a  sufrir  pérdidas,  daños  y  degradación—  es  producto  tanto  de  las  decisiones  históricas  sobre  la  infraestructura  urbana  como  del  cambio  climático.  
Hay que cambiar los guiones por paréntesis...

**Comment by Didigar** [comment]
@ovisnigra hay que darle un espacio después de un paréntesis...
En cuanto a la innovación del trabajo en la frontera, en MEGADAPT se parte de la tesis de que las normas so-ciales, valores, reglas y relaciones que subyacen la miría-da de decisiones de actores públicos y privados (o sea, la infraestructura # suave)es tanto o más importante para la vulnerabilidad socio-hidrológica de la Zona Metro-politana de la Ciudad de México que la infraestructura hidráulica dura.

**Comment by ovisnigra** [comment]
Hechas (la segunda es de la ficha de Transdisciplina).
