### ISSUE TITLE
Formación Ficha Modelación hidrológica #IAI

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#19]
NAD - En espera de solicitud de corrección. Agregar nuevas figuras y reformar.

**Comment by ovisnigra** [comment]
Revisadas e incorporadas las últimas correcciones. Favor de revisar y cerrar @Nayita

**Comment by Nayita** [comment]
Revisada

**Comment by ovisnigra** [comment]
Formando nuevamente la ficha con la última versión del texto. 

Observaciones: 
1. El título anterior decía: **Modelación hidrológica de cuencas urbanas y rurales**, en la nueva captura dice sólo **Modelación hidrológica**
2. El archivo de Word conserva el diagrama de flujo que ya se había eliminado, así como el pie de figura anterior.
3. Ya no hay referencia en el texto a la figura 2. En la formación anterior, estaba al final del último párrafo del texto de la ficha.
4. En la bibliografía se escribe el año de manera distinta (igual que en la ficha de modelación multicriterio, ver ese issue).

**Comment by Nayita** [comment]
Gracias por las observaciones. Las comento con Diana y las resolvemos y te notificamos.

**Comment by ovisnigra** [comment]
Vale

**Comment by Nayita** [comment]
Te respondo:
1.El título queda como Modelación hidrológica.
2.Haz caso omiso del diagrama de flujo. Sólo van las figuras nuevas que hiciste para esta ficha.
3.Por favor, agrega (Fig. 2) en el mismo sitio. Se les fue cuando la revisaron y cambiaron el texto según Diana.
4. Diana me dice que los años de la biografía van entre paréntesis. Diana está nuevamente corrigiendo bibliografía de todas las fichas.

Una disculpa por los errores y las tardanzas

**Comment by ovisnigra** [comment]
ok en los primeras tres puntos.

En el punto 4 Ojo: ¿Dónde piensan hacer las correcciones a la bibliografía? ¿En Word o en InDesign? ¿Cuál será a mejor manera para integrar a la formación?

**Comment by Nayita** [comment]
Lo hará Diana en InDesign. Coloca estos archivos también donde te dijo Diana. Gracias

**Comment by ovisnigra** [comment]
ya revisada bibliografía y formación. actualizados ID y PDF en **Fichas formadas IAI (PDF + ID)**

**Comment by Nayita** [comment]
ok, muchas gracias

**Comment by ovisnigra** [comment]
terminada. cierro issue
