### ISSUE TITLE
Hacer HTML de las gráficas que se utilizaron en la presentación #MEGADAPT

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#207]
Falta preguntar a Paola información de línea de custodia.

**Comment by Nayita** [comment]
Hacer las gráficas de Yosune

**Comment by Didigar** [comment]
ya esta la de suministro de agua con annotate para porcentaje sin espacio en carpeta ¡¡

**Comment by Nayita** [comment]
Falta las gráficas de Yosune y Andrés. No tenemos los csv y no corren los códigos para ponerlas estilo lab.

**Comment by Nayita** [comment]
hecho
