### ISSUE TITLE
Correcciones y cambios a Presentación #Megadapt #Diputados

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#215]
Incorporar texto del Director (luis quedó de mandarlo, mandar recordatorio). 

Pasar presentación a proporciones 4:3

**Comment by ovisnigra** [comment]
Ya terminé de pasar correcciones y la presentación a formato 4:3. Sólo me falta consultar unas dudas con Nadia. En cuanto lo haga cierro el _issue._

**Comment by ovisnigra** [comment]
Revisar con Fidel presentación para ver ajustes

**Comment by edithvilla** [comment]
Correcciones a la presentación (jueves 11 de mayo)

PRESENTACIÓN
1. Falta por agregar
             La gráfica de Andrés Baeza (Sergio)
             La captura de pantalla de NetLogo (Nadia y Diana con la ayuda de Fidel)

PLATAFORMA
1. Se realizó la migración de la obtención de las imágenes y diapositivas de la carpeta de Sergio a Q:\Plataforma\Slides_presentacion_mayo_2017

2. Se necesita migrar los HTML y las imágenes de las leyedas de patung a magrat (@serranoycandela)
3. Falta hacer correcciones en los mapas con la aprobación de @PaolaGomezPriego 
          Eliminar el título (Fidel)
          La leyenda hacerla más grande (Sergio)
          Cambiar las categorías  de las leyendas por categorías lingüisticas de los mapas de Encharcamientos y Enfermedades Gastrointestinales (Sergio)

4. Para los mapas de crecimiento urbano se necesita:
            Agregar a geoserver la capa de la zona urbana actual en tono de rosa más claro (Edith y Sergio deberá de dar el tono)

5. A las gráficas de pérdida de cobertura se les debe de corregir (@Nayita y @Didigar )
            El color, de rojo a magenta (checar la paleta de colores) 
            El tamaño del título 
            Las faltas de ortografía

6. Revisar el despliegue en geoserver de las capas de Abastecimiento y Antigüedad de la infraestructura (@edithvilla)

7. Mejorar el estilo de la Graficas_Inundacion-escasez.png  (@ovisnigra)

**Comment by edithvilla** [comment]
Hoy viernes 26 de mayo, quedó lista la presentación de los diputados

Se actualizaron las leyendas de los mapas, se colocó en la plataforma el gif de crecimiento urbano.
se actualizó la gráfica de Andrés
se actualizaron los colores de los mapa
