### ISSUE TITLE
Pruebas de contenido para página web LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#218]
Diana mandará texto (de preferencia capturado con estilos en Markdown) con texto para subir a página de Lancis.

MAndé a Diana links y archivos para que explore el marcaje en Markdown.

**Comment by ovisnigra** [comment]
Diana mandó archivo por correo.

No está bien hecha la conversión a MarkDown. Solicito mandar de nuevo el Word.

**Comment by ovisnigra** [comment]
> ¿Tienes el texto original de Word? ¿Me lo podrías mandar como estaba antes de que le pusieras los estilos de Markdown? Estoy teniendo algunos problemas y dudas con el formato, por eso quiero verlo como estaba en el original. Gracias de antemano, saludos.

**Comment by Didigar** [comment]
Si te mando el link donde esta.. es el anexo 1 ...
https://www.dropbox.com/work/IAI/informes%20iai/4_informe_cuarta_entrega_febrero_2017/Anexos/Anexos%20febrero-17?preview=Annex+1+-+Sustainability+science+Lit+Review.docx

**Comment by ovisnigra** [comment]
Recibido. Gracias
