### ISSUE TITLE
corregir gráfica de presentación universum G_Turismo_a_México

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#220]
@ovisnigra Ya la edite, te agregue para que estes enterado, edité en r que los datos del eje de la y ... la gráfica ahora se llama G_Turismo_Mex_v2.1png y también guarde un pdf y el AI corregido ... hay dos versiones de png una ennegrillas y otra sin negrillas
aqui está el link:

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_Turismo_Mex_v2.ai

 https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_Turismo_Mex_v2.1png.png

**Comment by ovisnigra** [comment]
gracias. ya las estoy revisando
