### ISSUE TITLE
Realizar nueva gráfica de visitantes a México (solo un día)

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#221]
@ovisnigra  Esta va a ser la nueva grafica ... no estoy segura de si es una aparte o debe de ir junto con la de turistas totales a México, de cu
alquier forma estan las dos opciones ... te mando dirección de donde se encuentran el png el pdf y el AI

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Nuevas

Habra que reunirnos con Paola para ver que diapositivas se quedan y cuales se van... a mi ya me había comentado de algunas... te agrego lo de las proporciones en la misma presentación y haré un nuevo issue (desde luego creare una versión nueva para poner los datos de las proporciones)

**Comment by ovisnigra** [comment]
¿En qué presentación estás agregando lo de las proporciones?

**Comment by Didigar** [comment]
aun no la tengo porque no se muy bien cuales diapositivas van a quedar en la presentación pero haré una copia nueva y te mando el link

**Comment by ovisnigra** [comment]
por ejemplo 

> esto
