### ISSUE TITLE
Realizar gráfica de humedales costeros para Presentación 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#231]
@ovisnigra Hola aqui te dejo el link de la imagen png y del pdf de la nueva gráfica con los datos de humedales 
https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_HumCos.pdf

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Finales?preview=G_HumCos.png

**Comment by ovisnigra** [comment]
Recibidas :)
