### ISSUE TITLE
Imágenes para presentación diapo13 pérdida de selvas y matorrales  

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#232]
@ovisnigra Aqui estan las imagenes de pérdida de selva y matorrales
De matorral hay dos ve cual te gusta mas ...

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Figuras?preview=P+de+S+Lacandona+(Fulvio+Eccardi).jpg

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Figuras?preview=6_fto_matorral_desertico+chih.jpg

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Figuras?preview=TEHUACAN+matorral.jpg

**Comment by ovisnigra** [comment]
Recibidas. Gracias
