### ISSUE TITLE
Agregar notas a diapositivas de la presentación 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#233]

**Comment by Didigar** [comment]
@ovisnigra los comentarios y demas las hice sobre la presentación que nos corrigió Pao... ya está, dime si quieres que te ayudo en algo más...
saludines

**Comment by ovisnigra** [comment]
creo que ya. trabajo en las imágenes que me faltan y mañana reviso los últimos detalles. Saludos

**Comment by Didigar** [comment]
@ovisnigra oye que crees... los colores están mal en la leyenda de la gráfica de endeudamiento pero no se que paso no puedo modificar el script porque lo hice en la otra compu y blabla ... hay que cambiarle los colores, es decir los datos estan bien pero la leyenda esta mal 
El rosa (puerto vallarta) corresponde a Bahia banderas (color azul)
el azul (bahia banderas) corresponde a benito juarez (color rojo)
el rojo (benito juarez) corresponde a puerto vallarta (color rojo)
el verde (solidaridad) es correcto le corresponde el color verde 
cualquier duda nos hablamos...
Por cierto me comento Paola que tienen que ver eso de las flechas que si vas a vernir mañana o a que hora nos comunicamos ....

**Comment by Didigar** [comment]
ya la pude editar ... asi debe quedar 
https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Nuevas?preview=G_EndeudamientoV.png

https://www.dropbox.com/work/Presentaci%C3%B3n%20UNIVERSUM/Procesamiento/Graficas/Nuevas?preview=G_EndeudamientoV.pdf

creo que es mas facil cambiarle solo los colores en la que ya tenemos como ves??? porque a esta le falta editar color, los años, etc

**Comment by ovisnigra** [comment]
ya la había arreglado. La acabo de integrar, a ver cómo la ves
