### ISSUE TITLE
Minuta reunión Sergio Flores

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#235]
Edith: pon todo lo que nos tienen que entregar.

**Comment by edithvilla** [comment]
Sergio Flores nos proporcionará:

1. Zona urbana 2015
2. Restricciones con categorías

**Comment by edithvilla** [comment]
Mandé correo recordatorio a Alonso de la capa de zona urbana 2015
