### ISSUE TITLE
Figura Vulnerabilidad para Ficha Vulnerabilidad

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#24]
NAD/PAO - Diagrama de Vulnerabilidad. En revisión del material para iniciar figura

**Comment by ovisnigra** [comment]
Enviada propuesta para su revisión

**Comment by ovisnigra** [comment]
Se cancela y se sustituye con nuevo esquema entregado por Paola

**Comment by ovisnigra** [comment]
Terminada figura nueva. en espera de revisión y aprovación para incorporar en ficha.

**Comment by ovisnigra** [comment]
Ya está el esquema. Me gustaría que lo revises Paola a ver si interpreté bien el boceto. Lo puedes ver directo en la ficha (que también ya está formada (sólo falta pie de figura)

link:
https://www.dropbox.com/sh/vkqv4bw55endx6i/AABCoLhQFd6dXLfCUqFywQ2da?dl=0

**Comment by PaolaGomezPriego** [comment]
No me gusta que no parece un mapa de la ciudad de méxico. Además la leyenda parece un chipote bastante feo..

**Comment by ovisnigra** [comment]
sí, está muy simple. ya la estoy retrabajando

**Comment by ovisnigra** [comment]
ya está la nueva versión. mismo lugar

**Comment by PaolaGomezPriego** [comment]
No se sigue gustando que no quedó como la Ciudad de México. pero ya queda aceptado..

**Comment by PaolaGomezPriego** [comment]
mmmhh ya viste que el tamaño de fuente sea lo suficientemente grande para que se vea en la ficha?

**Comment by PaolaGomezPriego** [comment]
Si la respuesta es si.. puedes cerrar el issue

**Comment by ovisnigra** [comment]
Comentario: Quedamos que tenía que ser un mapa genérico, ya que solo los de aquí conocen la ciudad de México. 

Sí, la tipografía está al tamaño que he usado en todas las fichas (8-9 pt).

Cierro
