### ISSUE TITLE
Nueva grafica boxplot presentación congreso

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#259]
@ovisnigra hola ya cambie la grafica pero no se muy bien cual es la paleta de colores ...segun yo el rojo y el azul si estan bien pero el verde no...
Te pongo el link de donde está con el nuevo formato
 Q:\Procesamiento\Graficas\VulnerabilidadPolitica\G_vulnera

**Comment by Didigar** [comment]
@ovisnigra  también es la de G_escasez

**Comment by ovisnigra** [comment]
ok. la reviso. Gracias

**Comment by Didigar** [comment]
@ovisnigra ya le puse las lineas de los caurtiles checalas...
Q:\Procesamiento\Graficas\VulnerabilidadPolitica

**Comment by ovisnigra** [comment]
La nueva versión de las gráficas:

Q:\Procesamiento\Figuras_&_Graficas_Presentacion_Congreso\**Graficas_Inundacion-escasez_v2.png**

Ya quedaría así para la presentación pero de todos modos Paola quiere que modifiques el escript para que quede lo más parecido a la que te mando.

Los valores del gris y el amarillo son: #b3b3b3 y #faa916 respectivamente. Saludos

**Comment by Didigar** [comment]
Ya quedaron con nuevo formato !!
