### ISSUE TITLE
Formación lista de Participantes #IAI

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#26]
DI - En espera de insumos y solicitud para formar lista.

**Comment by ovisnigra** [comment]
Recibidos insumos y lista. En espera de iniciar formación y recopilación de logotipos

**Comment by ovisnigra** [comment]
Ya hice una propuesta de formación. Tengo varias dudas y algunos logotipos que o encontré (puse un asterisco en estos casos).
Cuando llegue Paola, comentamos las dudas por teléfono, creo que será más fácil.

EL InDesign y su PDF están en la carpeta de fgormación de fichas:
https://www.dropbox.com/sh/g23cbexvs1jbse7/AABYRvxrSPQVmCX_crU8yEV-a?dl=0

**Comment by PaolaGomezPriego** [comment]
se ve bien. Paola no llega hasta las 4 pm (al curso).  que lo revise Bertha para ver si tiene alguna recomendación de logos.

**Comment by ovisnigra** [comment]
No sé si ya se lo hicieron llegar a Bertha. se lo envío para que lo pueda revisar.

**Comment by Didigar** [comment]
Ya aregue CENTLI en ID

**Comment by ovisnigra** [comment]
chido. 
ya se entregó con los logos pendientes. Se hará revisión para futuras entregas, supongo

**Comment by Didigar** [comment]
perfecto
