### ISSUE TITLE
Figura para Presentación (R) - Sistema de integración Síntesis y estrategia

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#27]
PAO - Enviada para su revisión.

**Comment by ovisnigra** [comment]
tengo hasta el lunes para presentar nueva propuesta

**Comment by PaolaGomezPriego** [comment]
¿Cuál es la pregunta?

**Comment by ovisnigra** [comment]
Hay dos propuestas nuevas en PNG, más un borrador en PPT (basado en imagen previa de Línea de base triple). Las revisamos el lunes o el martes.

**Link a la carpeta:** https://www.dropbox.com/sh/vjy9lz4o7upr8pi/AAD-pmk36G-GC_tjt8Lfv4a9a?dl=0

**Comment by PaolaGomezPriego** [comment]
Ya vi las opciones, se las enseño a Luis.

**Comment by PaolaGomezPriego** [comment]
técnicamente ya quedó no?

**Comment by ovisnigra** [comment]
supongo que sí, aunque la cambió mucho y no me gustaron los colores, pero bueno.
