### ISSUE TITLE
Actualizar las leyendas de los mapas de la plataforma #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#284]
@ovisnigra 

Actualizar las leyendas de los mapas y el archivo se encuentra en:

Q:\Procesamiento\Imagenes\Titulos_Leyendas_mapas

archivo
Leyendas_mapas_epvm.ai

esta actualización tiene que quedar para mañana por favor para que Fidel pueda actualizarlas o nos diga cómo actualizarlas

**Comment by ovisnigra** [comment]
listas en las carpetas de Plataforma y Procesamiento
