### ISSUE TITLE
Mejorar los formatos de asistencia #LANCIS

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#285]
@ovisnigra 

mejorar el formato sin perder información de cómo viene, creo que el logotipo de lancis no es el más actualizado

el formato se necesita utilizar este viernes

**Comment by ovisnigra** [comment]
¿ondestán? ¿y la ruta?

**Comment by edithvilla** [comment]
Perdón, va la ruta

C:\Dropbox (LNCS)\Organización de planeación colaborativa\LANCIS_Formatos_Asistencia

**Comment by ovisnigra** [comment]
listos. con mis iniciales en la misma carpeta
