### ISSUE TITLE
Figura Paola Modelo Impacto Ambiental #Doctorado

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#292]
Yastá la figura que me pediste pa que la revises. En:

_Dropbox (LNCS)/Doctorado/Procesamiento/Figuras_

**Modelo general impacto ambiental.png**

**Comment by ovisnigra** [comment]
No estoy seguro de si ese fue el nombre que me dijiste, ahi me lo corrijes si hace falta.

**Comment by ovisnigra** [comment]
ya está actualizada a una nueva versión

**Comment by ovisnigra** [comment]
nueva nueva versión. + la siguiente figura con los preceptos

**Comment by PaolaGomezPriego** [comment]
Ya quedamos con esto, lo cerramos?

**Comment by PaolaGomezPriego** [comment]
y btw, el proyecto se llama OIPA

**Comment by ovisnigra** [comment]
ya. cierro
