### ISSUE TITLE
Rediseñar página web LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#298]
en proceso, el lunes 12 tendré lista la propuesta preliminar.

**Comment by ovisnigra** [comment]
Pueden empezar a explorar la página web en esta dirección: 

https://ovisnigra.github.io

(el url, por supuesto, es provisional)

Ya integré un par de fichas: 

https://ovisnigra.github.io/megadapt/sintesis
https://ovisnigra.github.io/megadapt/transdisciplina

Aún está pendiente revisar con ustedes la estructura del menú principal para saber dónde se integrará el contenido.

**Comment by ovisnigra** [comment]
Paola solicitó más pruebas de integración de información. Procedo a buscar y probar otra plantilla

**Comment by PaolaGomezPriego** [comment]
tenemos que retomar esto y tener algo arriba para la semana que entra.

**Comment by ovisnigra** [comment]
ok. no he podido terminar los cambios que platicamos, pero entre hoy y mañana los termino pa que lo revisemos el lunes.

**Comment by PaolaGomezPriego** [comment]
ya vi la página con Luis.  Mueve por favor los proyectos al área de planeación colaborativa.

**Comment by ovisnigra** [comment]
ok

**Comment by ovisnigra** [comment]
Paola: 

Tenemos pendiente el texto del Dr. Bojórquez y la presentación de IAI para incorporar a la página.

**Comment by PaolaGomezPriego** [comment]
el nombre del proyecto de IAI:  "Proyecto IAI CNR3108: Coping with hydrological risk megacities: Collaborative planning framework for the Mexico City Metropolitan Area"

**Comment by PaolaGomezPriego** [comment]
El riesgo hidrológico en megaciudades: esquema de planeación colaborativa para la Zona Metropolitana de la Ciudad de México.

**Comment by PaolaGomezPriego** [comment]
Ya escribí una síntesis para IAI, estoy en espera de VoBo de Luis

**Comment by PaolaGomezPriego** [comment]
La semblanza de Luis te la da Rocío.

**Comment by PaolaGomezPriego** [comment]
Los íconos que van a quedar dentro del área de planeación colaborativa son: Megadapt, IAI, PN, invasoras, publicaciones y Repechique

**Comment by edithvilla** [comment]
issue: 442

Proyecto: Monitoreo del estado de las invasiones biológicas de plantas en México
página web: http://www.unibio.unam.mx/invasoras/
insumo: en disco duro

Proyecto: Curso en línea de Ordenamiento Ecológico
página web: http://kinet.cuaed.unam.mx/educacion_continua/ordenamiento_ecologico/

Proyecto: Programa Ecológico Marino y Regional del Ordenamiento del Pacífico Norte
página web: http://magrat.mine.nu:8080/Versatile/
insumos: C:\Dropbox (LNCS)\Pacifico_Norte\Insumos\Pacífico_Norte_julio_2015\IV Propuesta\Mapa_gral_UGA.pdf

Proyecto: Peritaje en materia de impacto ambiental y social de las afectaciones del Aeropuerto Regional Barrancas el Cobre
insumos: en disco duro externo

**Comment by ovisnigra** [comment]
Actualización. viernes 2 de noviembre:

- ya tengo incorporados el tablero de proyectos a la página, aún me falta arreglar cosas para que quede bien
- Apensa recibí la semblanza de Luis que mandó Rocío, me falta incorporarla
- Solicité a @edithvilla (en el issue #442) que me diga cuáles son las imágenes que se pueden usar para presentar los proyectos
- No tengo nada de Repechique
- No he recibido tampoco las imágenes del anfiteatro nuevas, ni las fotos de las áreas que iba a mandar Rocío. En este momento le escribo.

Resumen: Sigo trabajando en lo que está pendiente y supongo que haremos la actualización a la página (con Rodrigo) hasta el lunes.

seguimos en contacto

**Comment by PaolaGomezPriego** [comment]
Luis dió instrucciones a Rocío para proveer las fotos de anfiteatro, planeación colaborativa, etc. 
@edithvilla  de los insumos gráficos mas sobresalientes y pone actualizaciones en issue #442
@dpedroza74  ofreció ayudarnos con una mini síntesis de Repechique y PN así como algunas fotografías.
@Didigar es responsable de las publicaciones realizadas desde 2010 por todo el equipo de Planeación Colaborativa

**Comment by PaolaGomezPriego** [comment]
Por cierto Sergio, quita lo de infraestructura y equipamiento de la pagina de APC

**Comment by PaolaGomezPriego** [comment]
https://ovisnigra.github.io sigue siendo la versión para revisar?

**Comment by edithvilla** [comment]
@ovisnigra @dpedroza74 @PaolaGomezPriego 

en el dropbox en la carpeta "Organización de planeación colaborativa"  está la carpeta "pagina_web", ahí estamos poniendo los insumos por proyecto

C:\Dropbox (LNCS)\Organización de planeación colaborativa\pagina_web

**Comment by ovisnigra** [comment]
recibidas las últimas notificaciones. voy revisando el nuevo material

https://ovisnigra.github.io sigue siendo la versión de revisión en donde voy incorporando cambios y haciendo pruebas. pueda haber momentos en que esté algo descompuesto porque estoy trabajando en ella.

**Comment by PaolaGomezPriego** [comment]
@Didigar va a hacer un markdown de las publicaciones para que sea mas fácil su integración a la página. Le pédí que agregara las presentaciones mas importantes.

**Comment by PaolaGomezPriego** [comment]
Sergio, elimina los comentarios de las áreas que no nos corresponden. dejaste por ahí un OJO revisar tiempos verbales.

**Comment by ovisnigra** [comment]
ok

**Comment by Didigar** [comment]
@ovisnigra aqui está las publicaciones y las presentaciones, lo hice en Atom, le puse lo mas que pude de formato, como encabezados, cursivas, listado, los links...
ubicación:
 https://www.dropbox.com/work/Organizaci%C3%B3n%20de%20planeaci%C3%B3n%20colaborativa/pagina_web/publicaciones_presentaciones

**Comment by Didigar** [comment]
@ovisnigra aqui está las publicaciones y las presentaciones, lo hice en Atom, le puse lo mas que pude de formato, como encabezados, cursivas, listado, los links...
ubicación:
dropbox/organización de planeación colaborativa/pagina_web/publicaciones_presentaciones

**Comment by ovisnigra** [comment]
@PaolaGomezPriego me falta el texto de introducción del proyecto IAI

**Comment by PaolaGomezPriego** [comment]
**1. Falta el texto de introducción del proyecto IAI**
Si para el lunes, Luis no contesta, te doy lo que tengo. 
**2.  Falta el texto de introducción del proyecto IAI**
Daniela lo entrega el lunes
**3. hay algunas cosas que me están mandando que no están en la lista de proyectos que según yo habíamos quedado.**
El 5. está mal. Son publicaciones. El curso en línea nunca estuvo en la lista. Edith y co.  se están tomando la libertad de agregar cosas que no van en la página aún, pero que se agregarán en un futuro próximo, como el curso en línea. La lista de proyectos que puse cuatro días en esta cadena es la que queda.
Con respecto a PN, Daniela nos va a dar un resumen el lunes como entrada a la página oficial. 
**4. Tengo duda entonces de dónde debe ir:
Lo que está mandando Diana (publicaciones_presentaciones)**
es una de las pestañas principales como dije en el número anterior. 
**5. lo que pusieron en la subcarpeta SIGPLAN**
No tengo idea que pusieron ahí, ignóralo hasta que averigüe el lunes. 
**6. Lo que está mandando Rocío, pues, aparte del Anfiteatro y del edificio, tengo entendido que debía haber fotos de las otras Áreas de Lancis. También me mandó links de videos que no sé que hacer con ellos. Ya le escribí pa preguntarle.**
Qué areas necesitas?  Nosotros tenemos la consigna de hacer planeación colaborativa y anfiteatro. De los videos, no se que te mando. 
7. el lunes se tendrá que acabar la página, pero la estructura debe estar lista y funcionando. Solo se agregarán contenidos de IAI, Repechique y PN.  Qué mas te falta?

Por favor cuando pongas listas, enumera para no tener que repetir tus comentarios.

**Comment by ovisnigra** [comment]
Te cito: 
> La lista de proyectos que puse cuatro días en esta cadena es la que queda.

(no encontré en la cadena tu lista de proyectos)

Basado en mi lista queda así:

1. Megadapt --> _manda a link oficial_
2. IAI --> _a página interna con introducción del proyecto y un tablero de fichas_
3. Pacífico Norte --> _al link del sistema de soporte o a página de presentación_
4. Invasoras --> _al link oficial_
5. Publicaciones --> _a página con listado (Diana)_
6. Repechique --> _a página con texto y fotos_

Creo que sólo me falta un texto de descripción para cada proyecto, para incorporar debajo de la foto y el título. Perdón, no lo había pensado ni pedido antes. Supongo que también podemos omitir eso si prefieren.

**Comment by PaolaGomezPriego** [comment]
Proyectos correctos. Para IAI, 
nombre: Proyecto IAI CNR3108: Lecciones de transdisciplina en la evaluación del riesgo hidrológico en megaciudades: esquema de planeación colaborativa para la Zona Metropolitana de la Ciudad de México.

en la descripción: 
En este proyecto se explora el avance metodológico, las lecciones aprendidas, y las barreras para la investigación transdisciplinaria durante la evaluación del riesgo socio-hidrológico de la Zona Metropolitana de la Ciudad de México.  Los ámbitos de estudio incluyen: el diseño del proyecto, la determinación de los actores sociales, el involucramiento de los actores sociales durante las distintas etapas de desarrollo del proyecto, la evaluación del aprendizaje social, las herramientas de traducción, comunicación y mediación, y el desarrollo de las capacidades internas para enfrentar los retos del proyecto.

**Comment by PaolaGomezPriego** [comment]
Por favor, pon las publicaciones como lo último. @Didigar  te están haciendo falta publicaciones de Luis.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra La página del anfiteatro sigue no teniendo buenas fotos. tampoco el área de planeación colaborativa.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra no se ve bien que las cajas de los proyectos tengan cada una un tamaño distinto.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra  Invasoras no se llama así. Pon los nombres completos en los títulos.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra como título de las fichas de IAI pon: Comunicación y transdisciplina: Fichas informativas del proyecto Megadapt

**Comment by Didigar** [comment]
Busque mas publicaciones y agregue otras tres @ovisnigra quedaron en la misma ubicación
  dropbox/organización de planeación colaborativa/pagina_web/publicaciones_presentaciones

**Comment by ovisnigra** [comment]
estoy aplicando estos cambios

**Comment by ovisnigra** [comment]
ya apliqué cambios.

**Comment by PaolaGomezPriego** [comment]
Sergio: no veo los cambios den la página de Lancis

**Comment by PaolaGomezPriego** [comment]
Sergio: Daniela no te ha dado sus aportaciones de Repechique y PN?

**Comment by PaolaGomezPriego** [comment]
Sergio: No se ven los cambios en tu página tampoco

**Comment by ovisnigra** [comment]
1. Los cambios están hechos en la página de pruebas ovisnigra.github.io
2. No. Daniela no me ha dado nada aún. Me dijo que quiere discutir cómo poner las cosas con Luis (y supongo que no ha podido hacerlo)
3. No le he pedido a Rodrigo que suba la página con cambios porque aún hay cosas pendientes que quisiera que discutiéramos. Por ejemplo: los textos descriptivos de los proyectos faltan en varios casos (los que dicen "Lorem ipsum etc...")

**Comment by PaolaGomezPriego** [comment]
@ovisnigra 
1. faltan fotos del área de planeación colaborativa. 
2. En la página de Luis aparece planificación y desgraciadamente decimos planeación. 
3. por favor, elimina la foto del enchufe del anfiteatro y algunas fotos aparecen movidas.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra 
4. La página de IAI sigue mal. No incluiste el cambio de nombre del proyecto.  
5. Las fichas se siguen poco estéticas por los distintos tamaños.
6. para IAI solo deja el logo de IAI y céntralo y agrégalo a cada ficha

**Comment by PaolaGomezPriego** [comment]
@ovisnigra 8. en Dropbox (LNCS)\Organización de planeación colaborativa\pagina_web\principal_apc\apc_general encontrarás el texto que reemplaza el texto general del área de planeación colaborativa

**Comment by PaolaGomezPriego** [comment]
@ovisnigra  9. en Dropbox (LNCS)\Organización de planeación colaborativa\pagina_web\PN\OEMRPN_index  encontrarás el texto de la página general de PN

**Comment by PaolaGomezPriego** [comment]
@ovisnigra  10. en Dropbox (LNCS)\Organización de planeación colaborativa\pagina_web\repechique\repechique_index encontrarás el texto de la página de repechique. Esta página si requiere de una galería de fotos que se encuentran en la misma carpeta.

**Comment by ovisnigra** [comment]
revisando instrucciones. 
comenzaré a aplicar hasta en la tarde o en la noche.
sigo pendiente

**Comment by PaolaGomezPriego** [comment]
@ovisnigra 11. actualizar los cambios solicitados por @Didigar de publicaciones con fecha de hoy.

**Comment by PaolaGomezPriego** [comment]
@ovisnigra 12. subir los cambios a la página buena

**Comment by Didigar** [comment]
@ovisnigra habrá forma de que aceptes los últimos cambios plis para que yo pueda editar algunos detalles que vi con Pao sobre ese último que sugerí cambios?????

**Comment by ovisnigra** [comment]
Hola @Didigar no me aparece ninguna solicitud tuya, me aparece que hiciste un _fork_ de mi repositorio, pero no has mandado solicitud con tus cambios a mi repositorio. El método del _fork_ me parece más complicado. 

La manera más fácil (que te había propuesto) es la siguiente:

1. abres mi repositorio en github desde esta dirección: https://github.com/ovisnigra/ovisnigra.github.io, 2. ubica el archivo que vas a modificar y lo abres ahí mismo, en la página.
3. das clic en el ícono del "lapicito" para que te permita editarlo.
4. una vez que hayas terminado de modificar, das clic en la parte de abajo donde dice **"Propose file change"**
5. y ya, de esa manera recibo tu solicitud de modificación (un "pull request") y la integro. Puedes hacer tantas como haga falta, pero siempre siguiendo el mismo método.

Supongo que nos hace falta un seminario/repaso de Github.

Si tienes dudas llámame. Salu2.

**Comment by ovisnigra** [comment]
@PaolaGomezPriego por ahora sólo tengo un par de dudas:

1. ¿Como deben aparecer las fotos de planeación colaborativa?

a) como un banner en la parte del título (igual que en la semblanza o en la del anfiteatro)? o
b) como un carrusel, es decir, igual que en la secuencia de la página del anfiteatro.
c) como una galería con miniaturas?
d) otra?

2. ¿Ya viste las fotos que envió Rocío? No sé si ha subido nuevas, pero las que había eran muy repetitivas y no muy buenas en mi opinión. Vuelvo a revisar, pero estaría bien conseguir algo mejor, creo.

sigo pendiente.

**Comment by Didigar** [comment]
@ovisnigra Eso hice, tal cual............ ok lo vuelvo a hacer y en cuanto termine te aviso para que veas si te manda la solicitud de los cambios

**Comment by ovisnigra** [comment]
ya apliqué los cambios en https://ovisnigra.github.io

siguen pendientes:

1. modificaciones a publicaciones (no he recibido actualización de @Didigar )
2. La galería de Repechique, aún es provisional. Le falta organización y agregar más fotos que hay en la carpeta.
3. @PaolaGomezPriego: No he recibido respuesta de acerca de las fotos de planeación colaborativa 
4. Una nueva duda: El collage de inundaciones ¿cómo lo generamos? ¿alguien me lo dará?
5. Aguanto lo de subir los cambios a la página buena hasta que den luz verde de subir así como está.

sigo pendiente (mañana estoy disponible después de las 11).

**Comment by edithvilla** [comment]
@ovisnigra @PaolaGomezPriego 

ya están las imágnes de inundaciones de este año, 
/pagina_web/iai
dime en que te puedo ayudar

**Comment by PaolaGomezPriego** [comment]
1. @Didigar qué pasó con la actualización de las publicaciones?
2. puedes poner una galeria como la del anfiteatro? esto implicaría reajustar el tamaño de las imágenes.
3. Rocío no te dió fotos de nuestra área?
4. @edithvilla sacó las imágenes, @ovisnigra  puedes hacer una galería tipo anfitreatro o un collage 
5. ya súbela con estos cambios.  lo que está en este momento está peor.

**Comment by PaolaGomezPriego** [comment]
6. Me acordé que Luis pidió que se subieran los videos que se han publicado de Lancis. Los podrías poner en la parte inferior de la página principal?

**Comment by ovisnigra** [comment]
OK. Voy mandando la solicitud a Rodrigo pa que se actualice la página oficial. Luego me pongo a trabajar en lo demás.

**Comment by ovisnigra** [comment]
Hola @rgarcia-herrera: 
Ya mandé _Pull-request_ con las actualizaciones a la página. ¿Me avisas si jala?

Saludos

**Comment by Didigar** [comment]
@PaolaGomezPriego  @ovisnigra 
Ya lo volvi a hacer, de plano si no funciona Sergio, aqui te dejo la ubicación donde subo el md de las correcciones que hice sobre el documento...
dropbox/Organizaciondeplaneacioncolaborativa/pagina_web/publicaciones_presentaciones10nov2017

**Comment by PaolaGomezPriego** [comment]
7. Corregir figura de vulnerabilidad en ficha de IAI

**Comment by ovisnigra** [comment]
ya están aplicadas las últimas correcciones solicitadas. Hago un nuevo _pull-request._

Sólo queda pendiente (sigo trabajando en ello) integrar las fichas faltantes de IAI, eso lo tendré listo el lunes.

**Comment by ovisnigra** [comment]
@PaolaGomezPriego @rgarcia-herrera 

Ya mandé nuevo pull-request con correcciones

**Comment by PaolaGomezPriego** [comment]
@rgarcia-herrera podemos actualizar la página para ya cerrar este issue?

**Comment by ovisnigra** [comment]
Rodrigo ya subió la última versión. Hay un par de detalles que aún hay que ajustar

1. Link al `home` desde todas las páginas
2. Flechas de los carruseles

A Rodrigo le encargaron hacer más cambios a partir de un replanteamiento de la estructura de la página.

**Comment by ovisnigra** [comment]
terminada esta etapa. se cierra issue y se continuará la cacería de erratas y correcciones ulteriores por otro canal, foro o issue.
