### ISSUE TITLE
Convocatoria Solicitud de Servicio Social 2017

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#31]
Enviada y aprobada

**Comment by PaolaGomezPriego** [comment]
Sergio, necesito que quites la carrera de Manejo Costero porque no me la han aceptado y ya necesito publicar la convocatoria. Todo lo demás queda igual.

**Comment by ovisnigra** [comment]
Listo. Ya están actualizados los archivos tanto en mi carpeta de diseño como en la de Servicio Social del DB (DropBox/Servicio Social)
