### ISSUE TITLE
Actualizar mapa de UGAS en Versatile #PN

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#339]
@marcoajh  por favor podrías ubicar en donde está la versión final?  para tenerlo a la mano y lo podamos actualizar en la plataforma

**Comment by marcoajh** [comment]
La version final es la que se está usando en el geovisualizador, habrá que revisar cuál es el problema al leer la columna de la tabla de datos del vectorial.

**Comment by marcoajh** [comment]
El problema estaba en el archivo de estilos (sld), ya está arreglado.
