### ISSUE TITLE
Hacer pruebas de color para fichas UGA web #PN

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#345]
Pruebas de color para UGA terrestres que aparecerán en la web del Ordenamiento.

**Comment by ovisnigra** [comment]
@marcoajh 

Ruta al PNG con los colores para las fichas web de UGA terrestres:

Dropbox (LNCS)\Pacifico_Norte\CarpetasTrabajo\Sergio\Colores UGA terrestres Web PN\Colores_web_fichas_UGA_terrestres_PN.png

**Comment by PaolaGomezPriego** [comment]
se cierra por no tener actualización de necesidades.
