### ISSUE TITLE
Crear acciones de Photoshop para facilitar la conversión a GIF animados

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#356]
Revisar con @edithvilla los nuevos GIF ys sus dimensiones para hacer las nuevas acciones.

+ Hacer un manual

**Comment by edithvilla** [comment]
@ovisnigra 
Ya están listas las imágenes para el GIF y se encuentran en la siguiente dirección del servidor
Q:\Procesamiento\Mapas\CrecimientoUrbano
en las carpetas:
e05
e06
e07
e08

**Comment by ovisnigra** [comment]
Las acciones ya están creadas pero para realmente automatizar hay que resolver algunos asuntos:

1. Ver la manera de que al exportar desde QGIS los PNG de los mapas tengan todos **exactamente** el mismo tamaño (en pixeles). De no lograr esto se complica la automatización en Photoshop.
2. Agendar una aesoría con Fidel para ver las opciones de escripteo de Photoshop (mandé links por correo) http://www.adobe.com/devnet/photoshop/scripting.html


PD: Hice un manual sobre cómo crear acciones en Photoshop, para reescalar a 1080 dpi de alto. Hay que incorporar instrucciones para:

* Cargar acciones ya pre-diseñadas.
* Crear acción específica para añadir leyendas.

**Comment by PaolaGomezPriego** [comment]
para terminar esto se requiere un programa de python para automatizar.. se cierra hasta nuevo aviso
