### ISSUE TITLE
Revisar las dos capas que entregó A Estrada #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#358]

**Comment by edithvilla** [comment]
@aleestrada 

Revisé las dos capas que me mandaste y tengo observaciones de las capas y los metadatos

Capa: c_lisa_p1
Column name no corresponde a los nombres de la tabla del vectorial y FALTA en los metadatos una columna "C_P1_SDER" que viene en la tabla del vectorial.
Title  me parece que está incompleto, por favor revísalo
Datum WGS84
Other contributors El nombre Ana Escalante está mal escrito


Capa:  c_lisa_p2
Coordenadas de la capa están en geográficas y deben de estar en métricas (EPGS: 32614)
Title  me parece que está incompleto, por favor revísalo
Datum WGS84
Other contributors El nombre Ana Escalante está mal escrito

Quedo en espera de las correcciones de los metadatos y la capa con las coordenadas en UTM 14N

**Comment by aleestrada** [comment]
The layers have been revised and corrected. 
The metadata and the corrected layers have been sent to Edith to their revision.
