### ISSUE TITLE
Completar la capa de desalojo primario #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#377]
A la capa de nodos de desalojo primario se le necesita agregar si corresponde a alguna lumbrera, planta de bombeo u otra cosa

**Comment by edithvilla** [comment]
@marcoajh 

Ya está el shape "Edith.shp" el cual tiene las delegaciones La Magdalena Contreras, Álvaro Obregón, Cuajimalpa y Benito Juarez. 
Q:\Procesamiento\InputModelos\AguaSuperficial\Nodos Septiembre\nodes

Y la base de datos de los "edges" de las mismas delegaciones:  db_edith_lluvias.ods y db_edith_secas.ods

Q:\Procesamiento\InputModelos\AguaSuperficial\Nodos Septiembre\edges

**Comment by Nayita** [comment]
Hecho. En espera de visto de bueno

**Comment by Nayita** [comment]
terminado  por fin!!!!!!!!!! Q:\Procesamiento\InputModelos\AguaSuperficial\Nodos_octubre\edges\test_lluvias_3.shp
