### ISSUE TITLE
Preparar capa de reporte de encharcamientos #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#378]
Tener lista la capa de encharcamientos con sus respectivos metadatos y el markdown de los análisis

**Comment by edithvilla** [comment]
Ya le mandé correo a Yosune y ella va a preparar los datos

**Comment by edithvilla** [comment]
@marcoajh 

aquí se encuentra la capa

Q:\CarpetasTrabajo\Yosune\Inundaciones\ShapeSever\SeveridadUmbral

**Comment by marcoajh** [comment]
@edithvilla @yosunita 
Ya hay una capa de encharcamientos, es:
Q:\MEGADAPT_integracion\layers\Final\ponding_v1.shp
Es la frecuencia de encharcamientos para el periodo 2007-2014, sólo quedan pendientes los metadatos.
