### ISSUE TITLE
Hacer plantilla de guión audiovisual para presentaciones Anfiteatro

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#383]

**Comment by ovisnigra** [comment]
terminada. lista para ponerla a prueba. 

`Plantilla_guion_presentaciones_Anfiteatro.potx` queda guardada en: `Dropbox (LNCS)\Presentaciones\Plantillas_Presentaciones`

**Comment by PaolaGomezPriego** [comment]
Está perfecta. puedes indicar como hacer una miniatura automática para que todos los que participen en las presentaciones lo sepan hacer?  Podemos cerrar issue.

**Comment by ovisnigra** [comment]
ok. lo de la miniatura automática requuiere (idealmente) algo de programación ¿abro un nuevo issue para eso?

**Comment by PaolaGomezPriego** [comment]
si.

**Comment by ovisnigra** [comment]
got it
