### ISSUE TITLE
Mapas para artículo Salud Alejandra #MEGADAPT

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#393]
Solicitado por Alejandra. Ya mandó insumos, falta solicitud en Word

**Comment by ovisnigra** [comment]
recibida solicitud de word

**Comment by ovisnigra** [comment]
Se cargaron los archivos terminados en la siguiente ruta:
Dropbox (LNCS)/ Megadapt_integración2/ Carpeta de trabajo/ AlejandraE/ mapas_megadapt.articulo_salud_ERL_2017

Los archivos finales son los de formato TIF y el archivo meastro es el **AI**

**Comment by ovisnigra** [comment]
aquí está el issue @aleestrada

**Comment by aleestrada** [comment]
Muchas gracias.
Ya envíe las figuras a Ana y Andrés para su VoBo.

**Comment by ovisnigra** [comment]
chiroliro

**Comment by ovisnigra** [comment]
se solicitaron más mapas suplementarios. Se creó la carpeta correspondiente en el mismo lugar con los nuevos mapas.

Dropbox (LNCS)/ Megadapt_integración2/ Carpeta de trabajo/ AlejandraE/ mapas_megadapt.articulo_salud_ERL_2017/mapas_suplementarios

Los archivos finales son los de formato `TIF`

**Comment by ovisnigra** [comment]
cerramos
