### ISSUE TITLE
Revisar la capa de salud que mandó Alejandra Estrada #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#403]

**Comment by edithvilla** [comment]
es una capa que no estaba completa, Alejandra la está revisando, quedo en espera de su respuesta

**Comment by edithvilla** [comment]
@marcoajh @aleestrada

Marco y Alejandra está revisando la capa, los agebs están incompletos

**Comment by edithvilla** [comment]
@marcoajh @aleestrada 

23 de octubre, aún no he recibido la capa geográfica

**Comment by edithvilla** [comment]
@aleestrada @marcoajh 
cómo va lo de la capa geográfica, Ale si ya está lista me la puedes mandar por correo por favor?
gracias

**Comment by marcoajh** [comment]
@edithvilla @aleestrada 
La capa ya está lista, está en el storage MEGADAPT_integracion/layers/Final/healt.shp. Sólo hacen falta los metadatos en markdown, aunque ya los tienes en excel. Puedes usar cualquier archivo .md para hacerlos o pásame la ubicación del excel y yo lo hago.

**Comment by edithvilla** [comment]
@marcoajh 
te mando la ubicación por favor podrías pasarlo a markdown?
Q:\Insumos\septiembre2017\AEstrada
ya copie la capa a esta carpeta

**Comment by marcoajh** [comment]
@edithvilla 
Ya está el archivo de metadatos, está en la carpeta layers/Final de Dropbox.

Ya puedes cerrar el issue.
