### ISSUE TITLE
Organizar la carpeta de Presentaciones en el dropbox #ORGANIZACIÓN APC

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#404]

**Comment by bibianamonsivais** [comment]
@ovisnigra ; aclarar qué significa la leyenda "Master" y "Actualizado" en el nombre de las presentaciones por organizar

**Comment by ovisnigra** [comment]
hola @bibianamonsivais ¿me puedes indicar la ruta de los archivos a los que te refieres? gracias
