### ISSUE TITLE
Manual para hacer miniaturas automáticas de slides (acciones/programación)

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#406]
Manual de uso/acciones/programación para hacer miniatura automática de slides.

Instrucción Paola (en issue #383):

> ¿puedes indicar como hacer una miniatura automática para que todos los que participen en las presentaciones lo sepan hacer?

**Comment by ovisnigra** [comment]
lo deseable sería hacer un escript en JavaScript para Photoshop. Por ahora avanzaré en la creación de las acciones y la explicación de su uso en combinación con el programa `FileRenamer`

**Comment by ovisnigra** [comment]
Ya quedó el manual. Se resolvió con una acción de Photoshop y un manual de uso. El manual terminado queda, por ahora en: 

`Dropbox (LNCS)\Material grafico-editorial LANCIS\Manuales_diseno`

el archivo se llama: `manual_crear_miniaturas_a_partir_de_slides.html`

**Comment by PaolaGomezPriego** [comment]
@Didigar, @Nayita, @bibianamonsivais puede hacer una prueba cada una por favor con base en el manual para ver si le falta algo?

**Comment by bibianamonsivais** [comment]
@ovisnigra, @PaolaGomezPriego nos pidió que hiciéramos una prueba, pero no encontramos el archivo "acciones_photoshop_presentaciones.atn" en la carpeta para poder cargarlo en Photoshop

**Comment by ovisnigra** [comment]
hola @bibianamonsivais , las acciones están en la carpeta

`Dropbox (LNCS)\Material grafico-editorial LANCIS\Manuales_diseno`

si tienen más dudas me dicen

**Comment by bibianamonsivais** [comment]
Gracias @ovisnigra !!!

**Comment by Nayita** [comment]
@ovisnigra cuándo se hacen las miniaturas?

**Comment by ovisnigra** [comment]
@Nayita las miniaturas se harán **siempre** para las presentaciones del Anfiteatro. Servirán para armar el guión de la presentación.

**Comment by PaolaGomezPriego** [comment]
Hay que modificar el powerpoint para que coincida con el protocolo

**Comment by PaolaGomezPriego** [comment]
@edithvilla

**Comment by PaolaGomezPriego** [comment]
Si para el lunes 13 de noviembre no hay comentarios, se da por manual completo y se cierra el issue.

**Comment by ovisnigra** [comment]
Ya no hubo comentarios. Cierro issue.

El archivo queda en: **ORGANIZACION_APC\iso\manuales\manual_crear_miniaturas_a_partir_de_slides**
