### ISSUE TITLE
Hacer figura del procedimiento de planeación colaborativa #ISO

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#407]
Guardar png en C:\Dropbox (LNCS)\Organización de planeación colaborativa\Protocolos\Figuras y nombrar : fi_iso_componentes_gestion

**Comment by PaolaGomezPriego** [comment]
el archivo de base  C:\Dropbox (LNCS)\Organización de planeación colaborativa\PPC-SIGC página 3

**Comment by Nayita** [comment]
Guardar png en C:\Dropbox (LNCS)\Organización de planeación colaborativa\Procedimientos\Figuras y nombrar : fi_iso_componentes_gestion

**Comment by ovisnigra** [comment]
listo. 

archivado como `fi_iso_componentes_gestion.ai` y `fi_iso_componentes_gestion.png`

en `Dropbox (LNCS)\Organización de planeación colaborativa\Procedimientos\Figuras`

**Comment by ovisnigra** [comment]
cierro issue
