### ISSUE TITLE
Mandar liga de datos originales de precipitación de SACMEX #Megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#417]
a Yosune

**Comment by edithvilla** [comment]
@yosunita, @PaolaGomezPriego, @marcoajh 

esta es el path donde puedes encontrar los datos de precipitación de sacmex

Q:\Insumos\agosto2016\SACMEX\BASE DE DATOS\ALTURAS E INTENSIDADES HISTORICAS
