### ISSUE TITLE
Arreglar la carpeta de lancis_sener-semarnat_11agpsto2017 #APC

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#421]
@ovisnigra 
ya está la tabla con la relación de los tiempos y las carpetas de las diapositivas que se ocuparon en la presentación de sener-semarnat. La tabla está en google drive, la hoja se llama "Sener-Semarnat"

Paso 2???? qué sugieres??

**Comment by ovisnigra** [comment]
pa empezar que me compartas la tabla. no puedo entrar al google drive. no sé si no me han mandado invitación a mi correo sbourguet@iecologia.unam.mx

**Comment by edithvilla** [comment]
ya te mandé la invitación, 
Paso 2: yo me voy a encargar de hacer la carpeta "slides" y ahí voy a colocar todos los "sl_" y el lunes que vengas al lancis la revisamos y acabamos de armar el resto de las carpetas

**Comment by ovisnigra** [comment]
ok. enterado

**Comment by edithvilla** [comment]
@ovisnigra
 ya tengo la carpeta de "slide" lista, los archivos nombrados "slide1, slide2, etc" está doblemente checado con el archivo de la presentación en pptx el lunes ya podríamos acabar de arreglar la demás carpetas y tener todo listo para hacer el guión.
