### ISSUE TITLE
Revisar el protocolo de MD-Html 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#422]
Hola @ovisnigra ya tengo algunos avances y además habrá que agregarle algunos detalles que comentamos hoy...

**Comment by ovisnigra** [comment]
le echaré un ojo. lo comentamos el lunes?

**Comment by Didigar** [comment]
@ovisnigra aqui est el protocolo si puedes echarle un ojo plis¡¡ 
https://www.dropbox.com/work/Organizaci%C3%B3n%20de%20planeaci%C3%B3n%20colaborativa/Protocolos?preview=protocolo_html_enproceso.docx

**Comment by Didigar** [comment]
@ovisnigra @aleestrada @PaolaGomezPriego @yosunita @bibianamonsivais @Nayita @edithvilla 
Los cambios que discutimos en la reunión sobre el protocolo de Md, son los siguientes:

- Las fechas que hay que poner al final del nombre de los archivos, se compone del día, mes y año, el día se compone de dos dígitos, el mes de tres letras (ver tabla siguiente) y el año se pone completo, cabe mencionar que todo va junto sin guiones bajos ni espacios.

Mes | Abreviatura
-- | --
enero | ene
febrero | feb
marzo | mar
abril | abr
mayo | may
junio | jun
julio | jul
agosto | ago
septiembre | sep
octubre | oct
noviembre | nov
diciembre | dic

Ejemplo:
07jun2017
-Se contará con un repositorio de librerías para facilitar el uso de las mismas.
-Los Markdown que se realicen para analizar datos y que su fin no sea la construcción de un mapa o una gráfica deberán tener la cadena custodia correspondiente (que especifique en la metodología la bd raíz y donde se encuentra), además de especificar en el nombre que son un Pre-procesamiento. Ejemplo:
pre_analisis_nombre del tema o archivo que se trabaja_fecha  
pre_analisis_vulnerabilidad_03feb2017

- Se propuso utilizar una herramienta llamada > lintr para revisar que los script estén correctamente estructurados pero la librería sólo se puede usar en la versión nueva de  R 3.4.2 y Rstudio 1.1.383, no está disponible para versiones anteriores.

**Comment by ovisnigra** [comment]
Algunos comentarios sobre este protocolo:

* Empezando por el título, no se está generando un Markdown ni un HTML, sino que a través de esos lenguajes de marcado se está generando una gráfica. Creo que un nombre más correcto podría ser: **Generación de gráficas en R con salida en HTML mediante R Studio y R Markdown**

* En el objetivo  y alcance se debería explicar el modo de trabajo en R Studio. Se pueden poner links a la página de [R Studio](http://rmarkdown.rstudio.com/lesson-1.html) donde se explica cómo funciona.

* Al final de la página 4 dice:
> El siguiente es un ejemplo con formato de un Md (los “#, *,” definen el tamaño y letras en negrillas): 

  Habría que precisar que los signos son parte del marcado en Markdown y más bien habrái que remitir a una página que explique cómo operan. Por ejemplo [esta](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf).

* También en la página 4 aún hay un "HTLM", la sigla correcta es H-T-M-L _(Hyper Text Markup Language). Convendría hacer una búsqueda en todo el documento.
