### ISSUE TITLE
Creación de carpeta actualizada de presentaciones #Lancis

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#423]

**Comment by edithvilla** [comment]
Ya cree la carpeta en el disco duro que estamos utilizando para los respaldos de la presentaciones.
La carpeta se llama:
dropbox_PRESENTACIONES
en esta carpeta por favor pongan las carpetas ya organizadas para que las comencemos a revisar.
Ya están las de
Nadia
Bibiana
Edith

Faltan:
Diana
Paola

**Comment by edithvilla** [comment]
@Nayita @Didigar 

la carpeta de "otras"
los archivos que se encontraron ahí se renombraron, se le eliminó la palabra otra.
el archivo: 
pr_educacion_capacitacion_24may2013.pptx
se re ubicó en la carpeta de pr_posgrado_creacion

la mayoría de las presentaciones se re ubicaron

**Comment by edithvilla** [comment]
@Nayita 

mañana podríamos por favor revisar la carpeta de "pr_otras" para verificar entre las dos si se reubican los archivo o no?

**Comment by edithvilla** [comment]
@Nayita @PaolaGomezPriego 

Queda pendiente la carpeta "otras" hasta que Nadia pueda revisar con Paola las presentaciones que se encuentra ahí y poderlas ubicar en el lugar apropiado.

También queda pendiente subir la carpeta "PRESENTACIONES"

**Comment by edithvilla** [comment]
@PaolaGomezPriego 
queda pendiente la carpeta de "Guadalajara" que esta carpeta tal vez debería de ir en "CAPACITACION/cursos_formales" tu que opinas?

**Comment by edithvilla** [comment]
este issue quedó listo
