### ISSUE TITLE
Hacer la transcripción de los audios de la presentación de diputados del 29 de marzo#MEGADAPT

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#434]
Los audios se encuentran en https://www.dropbox.com/work/MEGADAPT_integracion2/Presentaciones/Diputados_29marzo2017/Logistica

Se usarán el audio 1 y el 3 para hacer la transcripción. La primera hora la hará Edith (0:00:00- 1:00:00). Diana hará de 1:00:00-1:28:40, 1:57:57-2:10:16 (audio1), 0:00:00-0:20:00 (audio 3). Nadia hará del 0:20:00-1:19:01 (audio 3).
Se transcribirá todo excepto titubeos.

Cualquier duda preguntamos a Paola.

**Comment by edithvilla** [comment]
Ya está lista la transcripción de la primera hora, lo compartimos por google drive

**Comment by Nayita** [comment]
hecho
