### ISSUE TITLE
Mejorar la redacción de secciones de la página de Lancis #Lancis

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#437]
Las secciones son: Presentación, semblanza, anfiteatro y planeación colaborativa. 
La página donde están actualmente es: https://ovisnigra.github.io/

**Comment by PaolaGomezPriego** [comment]
@ovisnigra: Le podrías dar acceso a estas secciones para que las trabaje en word?

**Comment by PaolaGomezPriego** [comment]
Semblanza se elimina de la lista..

**Comment by ovisnigra** [comment]
Hola Esmeralda. 

Los archivos los puedes descargar de esta página: https://github.com/ovisnigra/ovisnigra.github.io

Ahí, verás un listado de archivos y carpetas en donde tendrás:

- `index.md` --> Corresponde a la Presentación.
- `semblanza.md`
- `anfiteatro.md`
- `planeacion_colaborativa.md` está en una carpeta llamada `planeacion_colaborativa

Los archivos **md** son archivos capturados en un lenguaje de etiquetado llamado [markdown](https://daringfireball.net/projects/markdown/). en esencia son simples archivos de texto plano que puedes abrir en cualquier procesador. 

Si los quieres trabajar en Word sugiero descargues un _plug-in_ llamado [Writage](http://www.writage.com/). Sólo funciona en Word para Windows y sirve para que puedas abrir y exportar a markdown desde Word.

Si tienes dudas, o se me olvidó algo, me dices.

**Comment by EsmeraldaOsejo** [comment]
Muchas gracias, lo bajo :)

**Comment by ovisnigra** [comment]
no hemos podido terminar la maniobra de cambio de repositorio. por ahora, trabaja los cambios aparte y luego me los mandas para que yo los integre. 

en cuanto tenga nuevo repositorio en donde puedas trabajar te mando la información.

Saludos

**Comment by ovisnigra** [comment]
Hola @EsmeraldaOsejo, ya está listo el nuevo repositorio en el que puedes seguir trabajando. La dirección del repositorio en Github sigue siendo:

https://github.com/ovisnigra/ovisnigra.github.io

La de Dropbox, probablemente ya no funcione, pero creo que ya no tiene caso que te la mande

me avisas cualquier duda. saludos

**Comment by EsmeraldaOsejo** [comment]
Gracias, Sergio.
Ya están listos y subidos los textos revisados de index.md y anfiteatro.md
En un rato subo el de planeacion_colaborativa.md

**Comment by ovisnigra** [comment]
solo recibí actualización de anfiteatro.md, no he recibido modificaciones de index.md

**Comment by EsmeraldaOsejo** [comment]
@ovisnigra, el de index.md ya estaba actualizado. Fue al que le hiciste merge desde el otro día. Yo lo veo actualizado.
Ya quedó listo y actualizado también el texto de planeacion_colaborativa.md
En cuanto a éste, yo sugeriría explicar planeación "de qué o para qué". También estaría bien agregar un poquito más de texto descriptivo bajo los encabezados correspondientes a los proyectos; con los nombres solos no basta para entender de qué van esas secciones, sobre todo "Educación, creación y fortalecimiento de capacidades”.
