### ISSUE TITLE
Buscar insumos para web LANCIS #APC

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#442]

**Comment by edithvilla** [comment]
@ovisnigra @PaolaGomezPriego 

Proyecto: Monitoreo del estado de las invasiones biológicas de plantas en México
página web: http://www.unibio.unam.mx/invasoras/
insumo: en disco duro

Proyecto: Curso en línea de Ordenamiento Ecológico
página web: http://kinet.cuaed.unam.mx/educacion_continua/ordenamiento_ecologico/

Proyecto: Programa Ecológico Marino y Regional del Ordenamiento del Pacífico Norte
página web: http://magrat.mine.nu:8080/Versatile/
insumos: C:\Dropbox (LNCS)\Pacifico_Norte\Insumos\Pacífico_Norte_julio_2015\IV Propuesta\Mapa_gral_UGA.pdf

Proyecto: Peritaje en materia de impacto ambiental y social de las afectaciones del Aeropuerto Regional Barrancas el Cobre
insumos: en disco duro externo

**Comment by ovisnigra** [comment]
hola @edithvilla, oye ¿qué imágenes se usarán para ilustrar los pryoectos? ¿no era eso parte de la búsqueda de los insumos? 

Gracias. saludos.

**Comment by edithvilla** [comment]
@ovisnigra 
donde te coloco los insumos? (las imágenes).
La pensaba poner en organización de planeación colaborativa (dropbox) pero veo que aún no actualizas esa carpeta.

**Comment by ovisnigra** [comment]
Paola me avisó que ya crearon una carpeta en 

`Dropbox (LNCS)/Organización de planeación colaborativa/pagina_web``
ahí está bien. gracias

**Comment by edithvilla** [comment]
@ovisnigra agregué un par de fotos del drone de Repechique
C:\Dropbox (LNCS)\Organización de planeación colaborativa\pagina_web\repechique\Fotos
