### ISSUE TITLE
Corregir errores de banco de datos final #OIPA

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#449]
1. Favor de trabajar en la última versión. @Didigar: poner aquí el nombre y ruta de la versión en la que trabajas. 
2. Hay registros sin año.

**Comment by Didigar** [comment]
@Nayita 
-Ya quedaron unificados en esta versión los estados y algunos municipios (algunos municipios tienen tres municipios en unos solo de un mismo estado, no se cual es el efectivo así que lo deje).
-Falta unificar Datos de las demás columnas porque tienen valores binarios (0/1) pero la mayoría tienen celdas vacías, hay que ponerles 0 ó 1 y no dejarla vacía...
-Hay celdas con años vacíos que se pueden sumir por la fecha de la gaceta pero también hay celdas que no tienen fechas en las gacetas.
-En número de las gacetas hay celdas vacías.
La base de datos a la que le corregí algunas cosas se encuentra aquí:

dropbox/Doctorado/Insumos/Banco_datos_MIA/Registro_Gacetas_GENERAL_revisar_9NOV_DEGA_para analisis

**Comment by PaolaGomezPriego** [comment]
favor de numerar los comentarios para dar seguimiento a éstos.

**Comment by PaolaGomezPriego** [comment]
1. agregar una columna que indique que abarca mas de un municipio y poner un municipio en la columna de municipios (y los otros en una segunda columna que se llame otrosmunicipios).
2. cuándo queda esto listo? no podemos avanzar sin esto. o explicar la razón para ver si podemos avanzar con el análisis. 
3. Ya se pidió que revisaran el resolutivo o la mia? 
4. no entiendo

5. cuándo queda la final para que podamos avanzar?

**Comment by Nayita** [comment]
@PaolaGomezPriego @Didigar 
Hola Paola, los comentarios anteriores fueron de Diana y ya los platiqué con ella. Contesto:
1. Hecho
2. Esta es una duda que tenía. Generalmente las celdas vacías es porque no se encontraron estos casos específicos. Se necesita poner los ceros para el análisis? Hay casos en los que no se encontró la información como el tiempo de resolución porque no hay fecha de resolución ni resolutivo para verificar.  Esto en concreto es mejor verlo el lunes para decidir que procede, viendo los casos en concretos porque en algunos casos los ceros si tienen un significado en específico, no sólo ausencia.
3. Hecho
4. Hecho

Ya también está la tabla de síntesis. Ya junté la tabla de Marbella que faltaba.
Resolviendo el punto 2 queda concluida la tabla. Ya actualicé lo faltante de Emilio también.
Saludos

**Comment by Nayita** [comment]
Actualización de la tabla de Síntesis

**Comment by Nayita** [comment]
hecho
