### ISSUE TITLE
Revisar carpetas de presentaciones ya terminadas de organización del Dropbox #APC

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#454]

**Comment by edithvilla** [comment]
las carpetas las vamos a revisar de la siguiente manera:
Edith revisa las de Diana
Diana revisa las de Nadia
Nadia revisa a Edith

Para saber qué carpetas son de cada quien necesitamos revisar el google drive.

La compilación de las carpetas se encuentra en el disco duro ADATA que está en custodia de Diana y Nadia.

ADATA:\dropbox_PRESENTACIONES\

**Comment by edithvilla** [comment]
Cualquier comentario lo deberemos anotar en el google drive en la columna de "Notas" para que quede registrado

**Comment by Didigar** [comment]
@Nayita  @edithvilla  @bibianamonsivais  @PaolaGomezPriego 
ya quedaron las carpetas de Nadia revisadas con sus respectivos comentarios ... revisé dos de presentaciones:
pr_cananea_fideicomiso_16ago2016
pr_otras

**Comment by Nayita** [comment]
@edithvilla @bibianamonsivais @PaolaGomezPriego @Didigar 
Terminé las carpetas de Edith. Las observaciones ya están registradas en la hoja del listado de las presentaciones.
También revisé dos carpetas de Bibiana, las de espejo_yucatan de ambas fechas. No hay observaciones de esas carpetas.
Carpetas revisadas:
pr_ lancis_espejo_yucatan_19may2017
pr_lancis_espejo_yucatan_24ago_2017
pr_lancis_peritaje_chihuahua_3mar2016
vi_lancis_drone

**Comment by edithvilla** [comment]
Ya revisé las de Diana y los comentarios están registrados en la hoja del listado de las carpetas del google drive
