### ISSUE TITLE
Actualizar el diagrama de integración de modelos de #megadapt 

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#459]
Solicitar a Sergio si necesita mejorar

**Comment by edithvilla** [comment]
@PaolaGomezPriego  @ovisnigra 

ya revisé con Luis el diagrama y solo hay dos cambios

**Comment by ovisnigra** [comment]
terminada corrección. queda en carpeta:

`Dropbox (LNCS)\Diseño gráfico LANCIS (Respaldo Sergio)\Megadapt IAI\Figuras generales Megadapt (Informes & Presentaciones)\Integración de modelos`

**OJO: ¿Hay que cambiar la versión en inglés también? ¿cuál sería la traducción?**

**Comment by edithvilla** [comment]
@ovisnigra 
Mapa de pozos en inglés

Map of wells

**Comment by ovisnigra** [comment]
ok. Queda la versión en inglés en la misma ruta, en la subcarpeta `fi_megadapt_integracion_modelos_EN`

**Comment by ovisnigra** [comment]
Paso la tarea de revisión y cierre de este issue a @edithvilla

**Comment by ovisnigra** [comment]
terminado. cierro
