### ISSUE TITLE
Editar fichas IAI, "Modelación hidrológica" y "Modelación multicriteria"

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#460]
Retomando...
1. En la ficha modelación multicriteria, en la referencia:
Lootsma, F. A. (1999). Multi-criteria decision analysis via ratio and difference judgement. Kluwer Academic, quitar link.
Publishers, Dordrecht.

2. Confirmo, en la ficha de "Modelación hidrólogica" el nombre es:
P. F., Ffolliott

**Comment by ovisnigra** [comment]
ya corregido e integrado. cierro issue
