### ISSUE TITLE
Asegurar que las presentaciones de anfiteatro corren en anfiteatro #megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [sostenibilidad-unam/planeacion-colaborativa#482]
Para mañana viernes 1ro de diciembre

**Comment by PaolaGomezPriego** [comment]
ya @marcoajh está instalando dropbox y encriptando y sincronizando las carpetas que se necesitan.

**Comment by edithvilla** [comment]
ya corre la presentación de los Diputados, desde el dropbox

**Comment by edithvilla** [comment]
ya están listas las presentaciones de sener-semarnat y la de los diputados

1 dic 2017, 1:30pm
