### ISSUE TITLE
Hacer las gráficas de la tabla de síntesis #OIPA

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#493]
Hola @Didigar:

Te envío la tabla corregida y terminada a tu correo para que puedas hacer las gráficas faltantes a primera hora. El archivo también ya está en el dropbox en la siguiente ruta www.dropbox.com/home/Doctorado/Insumos/Banco_datos_MIA.
Gracias

**Comment by Didigar** [comment]
Recibido y generando las nuevas gráficas y actualizando los datos de las anteriores
