### ISSUE TITLE
Formación Ficha Modelación Multicriterio

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#54]
Terminada. En espera de revisión y cierre @Nayita

**Comment by Nayita** [comment]
@ovisnigra Esta ficha ya se revisó, aceptó y cerro el día de ayer a las 14:10.

**Comment by ovisnigra** [comment]
En la revisión final de fichas se corrigió:

>Nadia: Sergio, hicimos una pequeña corrección a la ficha de modelación multicriterio en el archivo id. Me comenta Diana que tu haces el PDF para que lo hagas nuevamente, por favor. Gracias.

**Comment by ovisnigra** [comment]
Se revisó y se hizo el nuevo PDF. Cierro _Issue_
