### ISSUE TITLE
Formación Ficha Sistemas Socioecológicos

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#57]
NAD - Recibida solicitud y texto el miércoles 25 de enero. En espera de comenzar.

**Comment by Nayita** [comment]
@ovisnigra Dónde la puedo revisar? busqué en la carpeta de diseño gráfico lancis (respaldo Sergio) y no la encontré

**Comment by ovisnigra** [comment]
@Nayita Me equivoqué en el comentario. Ayer apenas recibí el texto y la solicitud. No la he comenzado aún. (Corrijo el comentario).

**Comment by Didigar** [comment]
@ovisnigra @Nayita estoy de metiche again en ichus ajenos....
Resulta que cambió una palabra del contenido, ya hice el cambio en el documento qeu esta en drop box https://www.dropbox.com/home/dise%C3%B1o%20gr%C3%A1fico%20lancis%20(respaldo%20sergio)/megadapt%20iai/Fichas%20Megadapt%20IAI/Sistemas%20Socioecol%C3%B3gicos
Creo que no la habías empezado pero es para que estén enterados y ya te mande la corrección en una solicitud.

**Comment by ovisnigra** [comment]
@Didigar y @Nayita me mandan la misma corrección (creo) con diferentes indicaciones con 4 minutos de diferencia y por diferentes medios. Está fallando la comuncación y la organización. Hubiéramos podido empezar por preguntarme si ya había comenzado la ficha (cosa que no he hecho, por cierto). Estas sobreposiciones me hacen perder mucho tiempo. Cuando lo resuelvan me dicen en qué queda por este medio. Gracias

PD: No creo tener que aclarar que no necesitamos solicitud de corrección en este caso, basta con que me actualicen el texto y me digan en dónde queda la versión final. También habría que empezar a ver qué onda con las figuras de esta ficha (no he recibido nada de eso).

Saludos

**Comment by Didigar** [comment]
@ovisnigra Nadia no te mando correcciones de la ficha de sistemas socioecológicos solo fui yo... ella estaba a cargo de esa ficha pero Luis ayer me dio esa corrección y me metí en su ichuuuu y solo la etiquete a ella  y a ti ( a ella para que estuviera enterada del cambio en la ficha)
no sabia si ya la habias comenzado o no perdón por mandar solicitud pero Pao me dijo que la mandara como corrección....
Sobre los logos esa me corresponde a mi ...
ya me dijo Nadia que le dijiste a ella que hay que buscar los logos de los participantes, requieres que te mande todos los logos de instituciones, gobierno y demás? o algunos en especifico no entendí muy bien.

**Comment by Nayita** [comment]
Sergio, yo no mandé ninguna corrección de esta ficha en específico. Desconozco a qué te refieras. Con respecto a la figura te comento que en la SOLICITUD, en comentarios adicionales te puse el nombre del archivo de la figura (Modelo General Megadapt v2). El pie de figura es Fig.1 Sistema socio-ecológico de MEGADAPT.

**Comment by ovisnigra** [comment]
Estoy hecho bolas, en efecto recibí una solicitud por dos vías distintas y pensé que había sido Nadia quien mandó una de ellas (como estaba arrobada). En fin, reviso lo de la figura para incorporarla. Sigo sin empezar esta ficha (estoy en la de vulnerabilidad).

Lo de los logos, supongo que será mejor comentarlo en el issue de la lista de actores. En cuanto pueda lo incorporo ahí a los comentarios (tampoco he comenzado esa ficha).

**Comment by ovisnigra** [comment]
Entonces confirmo. Si entendí bien el archivo de texto ya está actualizado en mi carpeta y no tengo que hacer nada. Hoy estaré haciendo esta ficha.

**Comment by Nayita** [comment]
Así es, confirmo esa información.

**Comment by ovisnigra** [comment]
Terminada formación con archivo revisado. Sólo queda pendiente confirmar el pie de figura (ya que la captura no lo incluía).

**Comment by Nayita** [comment]
El pie de figura es Fig.1 Sistema socio-ecológico de MEGADAPT. Gracias

**Comment by ovisnigra** [comment]
Correcto. También ya queda.

**Comment by Nayita** [comment]
Correcto
