### ISSUE TITLE
Formación Ficha Riesgo a la salud #IAI

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#58]
NAD - Recibida solicitud y texto de la ficha.

**Comment by ovisnigra** [comment]
Hola. ¿me puedes confirmar si hay una nueva versión de texto para esta ficha? Tengo la que mandaste con la solicitud, no sé si es de las que está pendiente por revisar.

Gracias

**Comment by Nayita** [comment]
Hice los cambios pero no te cargué el archivo. Lo vuelvo a hacer y la pongo en dropbox. Ando trabajando en mi casa

**Comment by Nayita** [comment]
ok lo de la figura. Ahora te consigo lo del pie de figura

**Comment by Nayita** [comment]
Ya está la ficha de salud en el dropbox. No consigo comunicarme con Paola para lo del pie de figura. En cuanto lo tenga te lo comento. Gracias

**Comment by ovisnigra** [comment]
OK. lo reviso. gracias

**Comment by Nayita** [comment]
Envío pie de figura: Fig. 1. Zonas vulnerables a enfermedades asociadas a inundaciones y escazes de agua.

Y se cita justo después de la primera oración de la segunda sección

**Comment by Nayita** [comment]
la cita ya está puesta en el texto que he vuelto a poner en el dropbox con esa corrección

**Comment by ovisnigra** [comment]
ok. lo aplico y te aviso. 

(No quito mi etiqueta para no perder esta corrección que no he hecho.)

**Comment by ovisnigra** [comment]
Listo. Ya actualizado también el PDF en la misma carpeta del ID.

**Comment by Nayita** [comment]
oki, gracias Sergio

**Comment by ovisnigra** [comment]
terminada. cerrada
