### ISSUE TITLE
Figuras Mapamundi y México con porcentajes P_Universum

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#63]
NAD/PAO - Platicadas con Paola, en espera de solicitud e insumos

**Comment by PaolaGomezPriego** [comment]
Nadia las manda en una hora.

**Comment by ovisnigra** [comment]
Ya están las figuras en la carpeta de este link para su revisión:

Link: https://www.dropbox.com/sh/4msbie0eqtrg7yc/AABeBXYHwpu5KGIrfsSu9qC9a?dl=0

**Comment by PaolaGomezPriego** [comment]
Ponle transparencia a las bolas y deja a un decimal en la segunda mundial. la bola gigantesca se ve fea.

**Comment by ovisnigra** [comment]
1. ¿Transparencia a las dos figuras?
2. La segunda mundial tiene una cifra de 0.08 ¿queda en 0.1?
3. Por cierto, no suman 100%

**Comment by PaolaGomezPriego** [comment]
1. si
2. si
3. haz que cuadren, la diferencia es de uno o dos puntos porcentuales no?

**Comment by ovisnigra** [comment]
hecho. el link es el mismo

**Comment by PaolaGomezPriego** [comment]
Junta Cancnún y Riviera Maya en la segunda que no se ve bien encimados.. La otra es Americas, eso incluye el continente completo.. y parece que está mas sobre america del norte..

**Comment by PaolaGomezPriego** [comment]
No corregiste lo de Cancún y Riviera Maya

**Comment by ovisnigra** [comment]
No era un cambio tan rápido lo había dejado para después. Ya lo hice.

**Comment by PaolaGomezPriego** [comment]
Gracias
