### ISSUE TITLE
Revisar portada y nuevas slides para presentaciones LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#67]
Añadir propuesta a las plantillas de Presentaciones Lancis usando la foto enviada por Paola 
**Ruta:** (\Diseño gráfico LANCIS (Respaldo Sergio)\Presentaciones generales & Folletos LANCIS\Auxiliares y diapositivas sueltas

**Comment by ovisnigra** [comment]
Terminar portada con Título.

Revisar plantilla poner nuevas eslaids, según instrucciones de Paola.

**Comment by ovisnigra** [comment]
Revisando protocolo y últimas presentaciones han salido nuevas slides que integrar. Estoy en eso

**Comment by ovisnigra** [comment]
terminado (sólo para la versión 16:9)

**Comment by PaolaGomezPriego** [comment]
Faltan las opciones para dos cuadros con texto, dos figuras, dos tablas, etc. Solo la opción una foto y texto.

**Comment by ovisnigra** [comment]
ok. reviso y las incorporo

**Comment by ovisnigra** [comment]
ya hay varias opciones para lo que pides. les cambié nombre para que sean más identificables. también incorporé nuevas opciones para textos resaltados
