### ISSUE TITLE
Figura en AI de aguas tratadas #Presentación universum

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#68]
Realice borrador, falta que el departamento de diseño gráfico mejore la imagen...

**Comment by ovisnigra** [comment]
recibida. con solicitud

**Comment by ovisnigra** [comment]
Para mi: Revisar borrador que hice con Paola.

**Comment by ovisnigra** [comment]
Lista. Revisar en la misma carpeta de Figuras Universum dentro de la subcarpeta **Figura Aguas tratadas** Link: https://www.dropbox.com/sh/4msbie0eqtrg7yc/AABeBXYHwpu5KGIrfsSu9qC9a?dl=0

**Comment by ovisnigra** [comment]
Ya inciorporada y corregida para la presentación. Cierro Issue.
