### ISSUE TITLE
Cambiar el color de marco conceptual y herramientas metodológicas fichas #IAI

### ISSUE THREAD

**Issue by Nayita** [sostenibilidad-unam/planeacion-colaborativa#83]
Cambiar el color de la cintilla

**Comment by ovisnigra** [comment]
¿Me pueden dar más instrucciones (más precisas)? ¿cambiar por cuál qué color? ¿Qué fue lo que no funcionó?

**Comment by ovisnigra** [comment]
estoy haciendo una pregunta y no me la contestan @Didigar. Etiqueté a @Nayita porque ella creó este issue. Necesito instrucciones. No basta con que creen el issue si no me dicen bien de qué se trata la corrección.

**Comment by Didigar** [comment]
Ahhh ya perdón, no me apareció hasta ahora creo que no lo actualice una disculpa, @ovisnigra ... @Nayita te dará las instrucciones

**Comment by Nayita** [comment]
Porque Paola dice que ambos tonos están muy parecidos. Al imprimir las fichas lo vimos

**Comment by Nayita** [comment]
Me refiero a la cintilla. Me expliqué?

**Comment by ovisnigra** [comment]
sí.

**Comment by ovisnigra** [comment]
Como no recibo respuesta de esto, decidí sólo modificar el azul de "Marco Conceptual" por uno un poco más claro. El color de Herramientas metodológicas lo dejo como estaba.

**Comment by Nayita** [comment]
Ok, si bastaba con cambiar uno. Veo que lo cheque Paola y te comento.

**Comment by Nayita** [comment]
Dónde podemos ver la ficha con el nuevo color?

**Comment by ovisnigra** [comment]
En la ficha de Transdisciplina

https://www.dropbox.com/sh/zjoxpgl1h1jau9p/AADQwiB3oxBIMw2CwLBCrokQa?dl=0

**Comment by Nayita** [comment]
Ya lo vio Paola, dice que no le encanta, pero que quede así. Cierro. Gracias
