### ISSUE TITLE
Obtener estadísticas del escenario e00 de SLEUTH

### ISSUE THREAD

**Issue by marcoajh** [sostenibilidad-unam/planeacion-colaborativa#85]
Debe indicarse la Superficie urbana de inicio.

Debe indicarse conjuntamente las categorías de 50 a 80 %

Debe indicarse conjuntamente las categorías de 80 a 100 %

**Comment by marcoajh** [comment]
Las tablas están en

**Comment by marcoajh** [comment]
Las tablas están en:
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/Estadísticas/stats_e00/
Se obtuvo un archivo para cada combinación extensión-año.
Extensión (mosaico o G9)
Año (2012, 2020, 2030, 2040, 2050 y 2060)
Falta Vo.Bo o correcciones de Paola

**Comment by PaolaGomezPriego** [comment]
Ya se están trabajando...

**Comment by marcoajh** [comment]
Correcciones hechas.
