### ISSUE TITLE
Editar ficha modelación multicriterio #IAI 

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#87]
Luis me dio varias correcciones en el texto, lo sustitui desde tu carpeta por el nuevo

**Comment by ovisnigra** [comment]
Ya trabajo en esta. Tomo el archivo que dice VO.BO del link que mandó Diana.

**Comment by ovisnigra** [comment]
Terminada edición con nueva versión del texto. 

OJO: Noté que en las referencias el año está escrito de manera diferente (en la primera entre paréntesis, en la otra, separado con un punto. Favor de revisar si está bien así o es un error y hay que uniformar.

**Comment by PaolaGomezPriego** [comment]
Inaceptable que le sigan mandando estos errores a Sergio. Habíamos quedado que se iban a mandar cosas completas y correctas.

**Comment by Didigar** [comment]
Las fichas que ya están revisadas tienen las referencias con año entre paréntesis y algunas ediciones

**Comment by ovisnigra** [comment]
¿eso qué significa? ¿que modificaron el word otra vez? ¿no habíamos quedado que ya no haríamos eso? ¿qué son "algunas ediciones"? 

Otra cosa: también habíamos quedado que cuando respondan un comentario me etiqueten (y quiten su etiqueta, si dejan las etiquetas yo no puedo saber a cuáles ya contestaron y cuáles debo revisar) plis porfis.

Las arrobo para asegurarme de que sí leerán esto @Didigar @Nayita.

**Comment by Didigar** [comment]
Lo corregi para que el archivo de texto no quede mal (se debe corregir I think) pero te pido que dejes los pdf aqui junto con el ID para aplicar las debidas correcciones sobre el ID (para no perder tiempo)
https://www.dropbox.com/home/IAI/Procesamiento/Fichas%20MEGADAPT%20IAI/PDF_Fichas-02-feb-17
las figuras van aca:
https://www.dropbox.com/home/IAI/procesamiento/Figuras/Figuras%20Fichas%20MEGADAPT
La cosa es que si yoto  de tu carpeta no se cual es la efectiva ....

**Comment by Nayita** [comment]
Ya te contestó Diana.

**Comment by ovisnigra** [comment]
Ok. Ya están los archivos de InDesign en la carpeta.

Ojo: Como sólo coloqué el InDesign sin las imágenes, al abrir les va a avisar que no las encuentra. No importa, abran el archivo sin actualizar los links y modifiquen el texto, yo luego re-actualizo los links a las figuras cuando haga el nuevo PDF (si tienen duda me avisan).

**Comment by Didigar** [comment]
@ovisnigra enterada, corrijo las fichas desde ID y te voy avisando cuales ya están desde aquí

**Comment by ovisnigra** [comment]
Ya acordé con Diana en crear una carpeta que contenga tanto los InDesgin como los PDF. En ella tendremos las últimas versiones formadas de las fichas.

**Comment by Didigar** [comment]
ya quedaron escritas uniformemente las referencias en los ID de las fichas ](https://www.dropbox.com/home/IAI/Procesamiento/Fichas%20MEGADAPT%20IAI/Fichas%20formadas%20IAI%20(PDF%20%2B%20ID))

**Comment by ovisnigra** [comment]
ültima corrección fue el 14 de febrero:

>Sergio, hicimos una pequeña corrección a la ficha de modelación multicriterio en el archivo id. Me comenta Diana que tu haces el PDF para que lo hagas nuevamente, por favor. Gracias. (NAD)

**Comment by ovisnigra** [comment]
Ültima corrección (14 feb):

>Sergio, hicimos una pequeña corrección a la ficha de modelación multicriterio en el archivo id. Me comenta Diana que tu haces el PDF para que lo hagas nuevamente, por favor. Gracias. (NAD)

Atendida. Revisé y generé de nuevo el PDF
