### ISSUE TITLE
Realizar ficha de modelación basada en agentes #IAI

### ISSUE THREAD

**Issue by Didigar** [sostenibilidad-unam/planeacion-colaborativa#88]
Hay que generar esta ficha @ovisnigra

**Comment by ovisnigra** [comment]
Recibí solicitud. Por iniciar.

**Comment by ovisnigra** [comment]
Mandé correo a Diana y Paola con comentarios respecto a la figura. Es muy grande y deberíamos ver cómo simplificarla y abreviarla. En espera de comunicarnos para ver qué procede.

**Comment by PaolaGomezPriego** [comment]
A mi ni me encanta esta figura pero Luis insistió y dijo que te encargaras de resolver que quedara. Lo que podemos hacer es dejar dos mapas en lugar de tres y las leyendas a la derecha.

**Comment by ovisnigra** [comment]
ok. voy viendo cómo puedo resolverlo. si tengo dudas les aviso.

**Comment by ovisnigra** [comment]
Terminada formación, figura y revisión de bibliografía (que hizo Diana). Los archivos de InDesign y el PDF finales están en la carpeta **Fichas formadas IAI (PDF + ID)**

**Comment by Didigar** [comment]
Enterada lo cierro
