### ISSUE TITLE
Hacer los mapas de SLEUTH #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/planeacion-colaborativa#90]
Hacer los mapas de SLEUTH para los escenarios 0 y 1

**Comment by edithvilla** [comment]
terminé los mapas del escenario 0

en espera que me entreguen escenario 1

**Comment by marcoajh** [comment]
Las salidas de SLEUTH para el escenario 01 ya están en:
/132.247.90.93/MEGADAPT_integracion/Procesamiento/OutputModelos/CrecimientoUrbano/e01/

**Comment by edithvilla** [comment]
Mapas listos y gif listo

Q:\Procesamiento\Mapas\CrecimientoUrbano
