### ISSUE TITLE
Obtener estadísticas para el grupo9 (control) del escenario e01 de SLEUTH

### ISSUE THREAD

**Issue by marcoajh** [sostenibilidad-unam/planeacion-colaborativa#93]
Cálculo de superficie en metros cuadrados

Deben indicarse conjuntamente las categorías de 50 a 80 %

Deben indicarse conjuntamente las categorías de 80 a 100 %

**Comment by marcoajh** [comment]
Las tablas están en:
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/Estadísticas/stats_e01/

Falta Vo.Bo o correcciones de Paola

**Comment by marcoajh** [comment]
Había un error en la capa de restricciones, ha sido corregido y se está corriendo de nuevo el modelo. 
Los archivos anteriores han sido eliminados.

**Comment by PaolaGomezPriego** [comment]
ok.

**Comment by Nayita** [comment]
En espera de que estén los datos para comenzar a procesarlos

**Comment by marcoajh** [comment]
Las tablas con los datos corregidos están en:
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/Estadísticas/stats_e01/

**Comment by Nayita** [comment]
Hecho, falta corregir escalas de gráficas
