### ISSUE TITLE
Figura Esquema de Sostenibilidad (diapo 10) Presentacion #Universum

### ISSUE THREAD

**Issue by ovisnigra** [sostenibilidad-unam/planeacion-colaborativa#94]
Recibí instrucciones de Paola (tomar de la diapo 10 de su presentación actual). 

Trabajo en ella

Nota: No hay solicitud, de ser el caso la llenamos después.

**Comment by ovisnigra** [comment]
Pongo el boceto en mi carpeta de Figuras Universum
https://www.dropbox.com/sh/4msbie0eqtrg7yc/AABeBXYHwpu5KGIrfsSu9qC9a?dl=0

Ojo: Falta ajustar colores y detalles finales. Por ahora sirva de referencia.

**Comment by PaolaGomezPriego** [comment]
Quito mi etiqueta hasta que haya nuevos cambios.

**Comment by ovisnigra** [comment]
Y hay propuesta con colores en carpeta:
https://www.dropbox.com/sh/4msbie0eqtrg7yc/AABeBXYHwpu5KGIrfsSu9qC9a?dl=0

Archivo: I_Esquema_sostenibilidad

**Comment by PaolaGomezPriego** [comment]
bien
